/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * ApostilamentoDTO
 */
public class ApostilamentoDTO {

    private String dataInclusao = null;

    private String descricao = null;

    private String numero = null;

    private String situacao = null;

    private String valor = null;

    public ApostilamentoDTO dataInclusao(String dataInclusao) {
        this.dataInclusao = dataInclusao;
        return this;
    }

    /**
     * Get dataInclusao
     *
     * @return dataInclusao
     *
     */
    @ApiModelProperty(value = "")
    public String getDataInclusao() {
        return dataInclusao;
    }

    public void setDataInclusao(String dataInclusao) {
        this.dataInclusao = dataInclusao;
    }

    public ApostilamentoDTO descricao(String descricao) {
        this.descricao = descricao;
        return this;
    }

    /**
     * Get descricao
     *
     * @return descricao
     *
     */
    @ApiModelProperty(value = "")
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public ApostilamentoDTO numero(String numero) {
        this.numero = numero;
        return this;
    }

    /**
     * Get numero
     *
     * @return numero
     *
     */
    @ApiModelProperty(value = "")
    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public ApostilamentoDTO situacao(String situacao) {
        this.situacao = situacao;
        return this;
    }

    /**
     * Get situacao
     *
     * @return situacao
     *
     */
    @ApiModelProperty(value = "")
    public String getSituacao() {
        return situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    public ApostilamentoDTO valor(String valor) {
        this.valor = valor;
        return this;
    }

    /**
     * Get valor
     *
     * @return valor
     *
     */
    @ApiModelProperty(value = "")
    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApostilamentoDTO apostilamentoDTO = (ApostilamentoDTO) o;
        return Objects.equals(this.dataInclusao, apostilamentoDTO.dataInclusao)
                && Objects.equals(this.descricao, apostilamentoDTO.descricao)
                && Objects.equals(this.numero, apostilamentoDTO.numero)
                && Objects.equals(this.situacao, apostilamentoDTO.situacao)
                && Objects.equals(this.valor, apostilamentoDTO.valor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(dataInclusao, descricao, numero, situacao, valor);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ApostilamentoDTO {\n");

        sb.append("    dataInclusao: ").append(toIndentedString(dataInclusao)).append("\n");
        sb.append("    descricao: ").append(toIndentedString(descricao)).append("\n");
        sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
        sb.append("    situacao: ").append(toIndentedString(situacao)).append("\n");
        sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
