/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * AuxilioBrasilPagoDTO
 */
public class AuxilioBrasilPagoDTO {

      private BeneficiarioDTO beneficiarioAuxilioBrasil = null;

  private LocalDate dataMesCompetencia = null;

  private LocalDate dataMesReferencia = null;

  private LocalDate dataSaque = null;

  private Long id = null;

  private MunicipioDTO municipio = null;

  private BigDecimal valorSaque = null;

  public AuxilioBrasilPagoDTO beneficiarioAuxilioBrasil(BeneficiarioDTO beneficiarioAuxilioBrasil) {
    this.beneficiarioAuxilioBrasil = beneficiarioAuxilioBrasil;
    return this;
  }

    /**
   * Get beneficiarioAuxilioBrasil
   * @return beneficiarioAuxilioBrasil
  **/
  @ApiModelProperty(value = "")
  public BeneficiarioDTO getBeneficiarioAuxilioBrasil() {
    return beneficiarioAuxilioBrasil;
  }

  public void setBeneficiarioAuxilioBrasil(BeneficiarioDTO beneficiarioAuxilioBrasil) {
    this.beneficiarioAuxilioBrasil = beneficiarioAuxilioBrasil;
  }

  public AuxilioBrasilPagoDTO dataMesCompetencia(LocalDate dataMesCompetencia) {
    this.dataMesCompetencia = dataMesCompetencia;
    return this;
  }

   /**
   * Get dataMesCompetencia
   * @return dataMesCompetencia
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDataMesCompetencia() {
    return dataMesCompetencia;
  }

  public void setDataMesCompetencia(LocalDate dataMesCompetencia) {
    this.dataMesCompetencia = dataMesCompetencia;
  }

  public AuxilioBrasilPagoDTO dataMesReferencia(LocalDate dataMesReferencia) {
    this.dataMesReferencia = dataMesReferencia;
    return this;
  }

   /**
   * Get dataMesReferencia
   * @return dataMesReferencia
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDataMesReferencia() {
    return dataMesReferencia;
  }

  public void setDataMesReferencia(LocalDate dataMesReferencia) {
    this.dataMesReferencia = dataMesReferencia;
  }

  public AuxilioBrasilPagoDTO dataSaque(LocalDate dataSaque) {
    this.dataSaque = dataSaque;
    return this;
  }

   /**
   * Get dataSaque
   * @return dataSaque
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDataSaque() {
    return dataSaque;
  }

  public void setDataSaque(LocalDate dataSaque) {
    this.dataSaque = dataSaque;
  }

  public AuxilioBrasilPagoDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AuxilioBrasilPagoDTO municipio(MunicipioDTO municipio) {
    this.municipio = municipio;
    return this;
  }

   /**
   * Get municipio
   * @return municipio
  **/
  @ApiModelProperty(value = "")
  public MunicipioDTO getMunicipio() {
    return municipio;
  }

  public void setMunicipio(MunicipioDTO municipio) {
    this.municipio = municipio;
  }

  public AuxilioBrasilPagoDTO valorSaque(BigDecimal valorSaque) {
    this.valorSaque = valorSaque;
    return this;
  }

   /**
   * Get valorSaque
   * @return valorSaque
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getValorSaque() {
    return valorSaque;
  }

  public void setValorSaque(BigDecimal valorSaque) {
    this.valorSaque = valorSaque;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuxilioBrasilPagoDTO auxilioBrasilPagoDTO = (AuxilioBrasilPagoDTO) o;
    return Objects.equals(this.beneficiarioAuxilioBrasil, auxilioBrasilPagoDTO.beneficiarioAuxilioBrasil) &&
        Objects.equals(this.dataMesCompetencia, auxilioBrasilPagoDTO.dataMesCompetencia) &&
        Objects.equals(this.dataMesReferencia, auxilioBrasilPagoDTO.dataMesReferencia) &&
        Objects.equals(this.dataSaque, auxilioBrasilPagoDTO.dataSaque) &&
        Objects.equals(this.id, auxilioBrasilPagoDTO.id) &&
        Objects.equals(this.municipio, auxilioBrasilPagoDTO.municipio) &&
        Objects.equals(this.valorSaque, auxilioBrasilPagoDTO.valorSaque);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beneficiarioAuxilioBrasil, dataMesCompetencia, dataMesReferencia, dataSaque, id, municipio, valorSaque);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuxilioBrasilPagoDTO {\n");
    
    sb.append("    beneficiarioAuxilioBrasil: ").append(toIndentedString(beneficiarioAuxilioBrasil)).append("\n");
    sb.append("    dataMesCompetencia: ").append(toIndentedString(dataMesCompetencia)).append("\n");
    sb.append("    dataMesReferencia: ").append(toIndentedString(dataMesReferencia)).append("\n");
    sb.append("    dataSaque: ").append(toIndentedString(dataSaque)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
    sb.append("    valorSaque: ").append(toIndentedString(valorSaque)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
