/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * BolsaFamiliaPagoDTO
 */
public class BolsaFamiliaPagoDTO {

    private BeneficiarioDTO beneficiarioBolsaFamilia = null;

    private LocalDate dataMesCompetencia = null;

    private LocalDate dataMesReferencia = null;

    private LocalDate dataSaque = null;

    private Long id = null;

    private MunicipioDTO municipio = null;

    private BigDecimal valorSaque = null;

    public BolsaFamiliaPagoDTO beneficiarioBolsaFamilia(BeneficiarioDTO beneficiarioBolsaFamilia) {
        this.beneficiarioBolsaFamilia = beneficiarioBolsaFamilia;
        return this;
    }

    /**
     * Get beneficiarioBolsaFamilia
     *
     * @return beneficiarioBolsaFamilia
     *
     */
    @ApiModelProperty(value = "")
    public BeneficiarioDTO getBeneficiarioBolsaFamilia() {
        return beneficiarioBolsaFamilia;
    }

    public void setBeneficiarioBolsaFamilia(BeneficiarioDTO beneficiarioBolsaFamilia) {
        this.beneficiarioBolsaFamilia = beneficiarioBolsaFamilia;
    }

    public BolsaFamiliaPagoDTO dataMesCompetencia(LocalDate dataMesCompetencia) {
        this.dataMesCompetencia = dataMesCompetencia;
        return this;
    }

    /**
     * Get dataMesCompetencia
     *
     * @return dataMesCompetencia
     *
     */
    @ApiModelProperty(value = "")
    public LocalDate getDataMesCompetencia() {
        return dataMesCompetencia;
    }

    public void setDataMesCompetencia(LocalDate dataMesCompetencia) {
        this.dataMesCompetencia = dataMesCompetencia;
    }

    public BolsaFamiliaPagoDTO dataMesReferencia(LocalDate dataMesReferencia) {
        this.dataMesReferencia = dataMesReferencia;
        return this;
    }

    /**
     * Get dataMesReferencia
     *
     * @return dataMesReferencia
     *
     */
    @ApiModelProperty(value = "")
    public LocalDate getDataMesReferencia() {
        return dataMesReferencia;
    }

    public void setDataMesReferencia(LocalDate dataMesReferencia) {
        this.dataMesReferencia = dataMesReferencia;
    }

    public BolsaFamiliaPagoDTO dataSaque(LocalDate dataSaque) {
        this.dataSaque = dataSaque;
        return this;
    }

    /**
     * Get dataSaque
     *
     * @return dataSaque
     *
     */
    @ApiModelProperty(value = "")
    public LocalDate getDataSaque() {
        return dataSaque;
    }

    public void setDataSaque(LocalDate dataSaque) {
        this.dataSaque = dataSaque;
    }

    public BolsaFamiliaPagoDTO id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     *
     */
    @ApiModelProperty(value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public BolsaFamiliaPagoDTO municipio(MunicipioDTO municipio) {
        this.municipio = municipio;
        return this;
    }

    /**
     * Get municipio
     *
     * @return municipio
     *
     */
    @ApiModelProperty(value = "")
    public MunicipioDTO getMunicipio() {
        return municipio;
    }

    public void setMunicipio(MunicipioDTO municipio) {
        this.municipio = municipio;
    }

    public BolsaFamiliaPagoDTO valorSaque(BigDecimal valorSaque) {
        this.valorSaque = valorSaque;
        return this;
    }

    /**
     * Get valorSaque
     *
     * @return valorSaque
     *
     */
    @ApiModelProperty(value = "")
    public BigDecimal getValorSaque() {
        return valorSaque;
    }

    public void setValorSaque(BigDecimal valorSaque) {
        this.valorSaque = valorSaque;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BolsaFamiliaPagoDTO bolsaFamiliaPagoDTO = (BolsaFamiliaPagoDTO) o;
        return Objects.equals(this.beneficiarioBolsaFamilia, bolsaFamiliaPagoDTO.beneficiarioBolsaFamilia)
                && Objects.equals(this.dataMesCompetencia, bolsaFamiliaPagoDTO.dataMesCompetencia)
                && Objects.equals(this.dataMesReferencia, bolsaFamiliaPagoDTO.dataMesReferencia)
                && Objects.equals(this.dataSaque, bolsaFamiliaPagoDTO.dataSaque)
                && Objects.equals(this.id, bolsaFamiliaPagoDTO.id)
                && Objects.equals(this.municipio, bolsaFamiliaPagoDTO.municipio)
                && Objects.equals(this.valorSaque, bolsaFamiliaPagoDTO.valorSaque);
    }

    @Override
    public int hashCode() {
        return Objects.hash(beneficiarioBolsaFamilia, dataMesCompetencia, dataMesReferencia, dataSaque, id, municipio, valorSaque);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BolsaFamiliaPagoDTO {\n");

        sb.append("    beneficiarioBolsaFamilia: ").append(toIndentedString(beneficiarioBolsaFamilia)).append("\n");
        sb.append("    dataMesCompetencia: ").append(toIndentedString(dataMesCompetencia)).append("\n");
        sb.append("    dataMesReferencia: ").append(toIndentedString(dataMesReferencia)).append("\n");
        sb.append("    dataSaque: ").append(toIndentedString(dataSaque)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
        sb.append("    valorSaque: ").append(toIndentedString(valorSaque)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
