/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * BPCDTO
 */
public class BPCDTO {

    private BeneficiarioBPCDTO beneficiario = null;

    private Boolean concedidoJudicialmente = null;

    private String dataMesCompetencia = null;

    private String dataMesReferencia = null;

    private Integer id = null;

    private Boolean menor16anos = null;

    private MunicipioDTO municipio = null;

    private BigDecimal valor = null;

    public BPCDTO beneficiario(BeneficiarioBPCDTO beneficiario) {
        this.beneficiario = beneficiario;
        return this;
    }

    /**
     * Get beneficiario
     *
     * @return beneficiario
     *
     */
    @ApiModelProperty(value = "")
    public BeneficiarioBPCDTO getBeneficiario() {
        return beneficiario;
    }

    public void setBeneficiario(BeneficiarioBPCDTO beneficiario) {
        this.beneficiario = beneficiario;
    }

    public BPCDTO concedidoJudicialmente(Boolean concedidoJudicialmente) {
        this.concedidoJudicialmente = concedidoJudicialmente;
        return this;
    }

    /**
     * Get concedidoJudicialmente
     *
     * @return concedidoJudicialmente
     *
     */
    @ApiModelProperty(value = "")
    public Boolean isConcedidoJudicialmente() {
        return concedidoJudicialmente;
    }

    public void setConcedidoJudicialmente(Boolean concedidoJudicialmente) {
        this.concedidoJudicialmente = concedidoJudicialmente;
    }

    public BPCDTO dataMesCompetencia(String dataMesCompetencia) {
        this.dataMesCompetencia = dataMesCompetencia;
        return this;
    }

    /**
     * Get dataMesCompetencia
     *
     * @return dataMesCompetencia
     *
     */
    @ApiModelProperty(value = "")
    public String getDataMesCompetencia() {
        return dataMesCompetencia;
    }

    public void setDataMesCompetencia(String dataMesCompetencia) {
        this.dataMesCompetencia = dataMesCompetencia;
    }

    public BPCDTO dataMesReferencia(String dataMesReferencia) {
        this.dataMesReferencia = dataMesReferencia;
        return this;
    }

    /**
     * Get dataMesReferencia
     *
     * @return dataMesReferencia
     *
     */
    @ApiModelProperty(value = "")
    public String getDataMesReferencia() {
        return dataMesReferencia;
    }

    public void setDataMesReferencia(String dataMesReferencia) {
        this.dataMesReferencia = dataMesReferencia;
    }

    public BPCDTO id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     *
     */
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public BPCDTO menor16anos(Boolean menor16anos) {
        this.menor16anos = menor16anos;
        return this;
    }

    /**
     * Get menor16anos
     *
     * @return menor16anos
     *
     */
    @ApiModelProperty(value = "")
    public Boolean isMenor16anos() {
        return menor16anos;
    }

    public void setMenor16anos(Boolean menor16anos) {
        this.menor16anos = menor16anos;
    }

    public BPCDTO municipio(MunicipioDTO municipio) {
        this.municipio = municipio;
        return this;
    }

    /**
     * Get municipio
     *
     * @return municipio
     *
     */
    @ApiModelProperty(value = "")
    public MunicipioDTO getMunicipio() {
        return municipio;
    }

    public void setMunicipio(MunicipioDTO municipio) {
        this.municipio = municipio;
    }

    public BPCDTO valor(BigDecimal valor) {
        this.valor = valor;
        return this;
    }

    /**
     * Get valor
     *
     * @return valor
     *
     */
    @ApiModelProperty(value = "")
    public BigDecimal getValor() {
        return valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BPCDTO BPCDTO = (BPCDTO) o;
        return Objects.equals(this.beneficiario, BPCDTO.beneficiario)
                && Objects.equals(this.concedidoJudicialmente, BPCDTO.concedidoJudicialmente)
                && Objects.equals(this.dataMesCompetencia, BPCDTO.dataMesCompetencia)
                && Objects.equals(this.dataMesReferencia, BPCDTO.dataMesReferencia)
                && Objects.equals(this.id, BPCDTO.id)
                && Objects.equals(this.menor16anos, BPCDTO.menor16anos)
                && Objects.equals(this.municipio, BPCDTO.municipio)
                && Objects.equals(this.valor, BPCDTO.valor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(beneficiario, concedidoJudicialmente, dataMesCompetencia, dataMesReferencia, id, menor16anos, municipio, valor);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BPCDTO {\n");

        sb.append("    beneficiario: ").append(toIndentedString(beneficiario)).append("\n");
        sb.append("    concedidoJudicialmente: ").append(toIndentedString(concedidoJudicialmente)).append("\n");
        sb.append("    dataMesCompetencia: ").append(toIndentedString(dataMesCompetencia)).append("\n");
        sb.append("    dataMesReferencia: ").append(toIndentedString(dataMesReferencia)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    menor16anos: ").append(toIndentedString(menor16anos)).append("\n");
        sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
        sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
