/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * CompraDTO
 */
public class CompraDTO {

    private String contatoResponsavel = null;

    private String numero = null;

    private String numeroProcesso = null;

    private String objeto = null;

    public CompraDTO contatoResponsavel(String contatoResponsavel) {
        this.contatoResponsavel = contatoResponsavel;
        return this;
    }

    /**
     * Get contatoResponsavel
     *
     * @return contatoResponsavel
     *
     */
    @ApiModelProperty(value = "")
    public String getContatoResponsavel() {
        return contatoResponsavel;
    }

    public void setContatoResponsavel(String contatoResponsavel) {
        this.contatoResponsavel = contatoResponsavel;
    }

    public CompraDTO numero(String numero) {
        this.numero = numero;
        return this;
    }

    /**
     * Get numero
     *
     * @return numero
     *
     */
    @ApiModelProperty(value = "")
    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public CompraDTO numeroProcesso(String numeroProcesso) {
        this.numeroProcesso = numeroProcesso;
        return this;
    }

    /**
     * Get numeroProcesso
     *
     * @return numeroProcesso
     *
     */
    @ApiModelProperty(value = "")
    public String getNumeroProcesso() {
        return numeroProcesso;
    }

    public void setNumeroProcesso(String numeroProcesso) {
        this.numeroProcesso = numeroProcesso;
    }

    public CompraDTO objeto(String objeto) {
        this.objeto = objeto;
        return this;
    }

    /**
     * Get objeto
     *
     * @return objeto
     *
     */
    @ApiModelProperty(value = "")
    public String getObjeto() {
        return objeto;
    }

    public void setObjeto(String objeto) {
        this.objeto = objeto;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompraDTO compraDTO = (CompraDTO) o;
        return Objects.equals(this.contatoResponsavel, compraDTO.contatoResponsavel)
                && Objects.equals(this.numero, compraDTO.numero)
                && Objects.equals(this.numeroProcesso, compraDTO.numeroProcesso)
                && Objects.equals(this.objeto, compraDTO.objeto);
    }

    @Override
    public int hashCode() {
        return Objects.hash(contatoResponsavel, numero, numeroProcesso, objeto);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CompraDTO {\n");

        sb.append("    contatoResponsavel: ").append(toIndentedString(contatoResponsavel)).append("\n");
        sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
        sb.append("    numeroProcesso: ").append(toIndentedString(numeroProcesso)).append("\n");
        sb.append("    objeto: ").append(toIndentedString(objeto)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
