/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * ConsultaFavorecidosFinaisPorDocumentoDTO
 */
public class ConsultaFavorecidosFinaisPorDocumentoDTO {

    private String codigoFavorecidoDespesa = null;

    private String codigoFavorecidoFinal = null;

    private String codigoListaCredor = null;

    private String codigoOrgaoSuperior = null;

    private String codigoOrgaoVinculado = null;

    private String codigoPagamento = null;

    private String codigoUnidadeGestora = null;

    private String dataCarga = null;

    private String municipioFavorecidoFinal = null;

    private String nomeFavorecidoDespesa = null;

    private String nomeFavorecidoFinal = null;

    private String orgaoSuperior = null;

    private String orgaoVinculado = null;

    private Integer skFatDW = null;

    private Integer skPessoaDespesa = null;

    private Integer skPessoaFinal = null;

    private String tipoDocumento = null;

    private String tipoFavorecidoDespesa = null;

    private String tipoFavorecidoFinal = null;

    private String tipoOB = null;

    private String ufFavorecidoFinal = null;

    private String unidadeGestora = null;

    private String valorFinal = null;

    public ConsultaFavorecidosFinaisPorDocumentoDTO codigoFavorecidoDespesa(String codigoFavorecidoDespesa) {
        this.codigoFavorecidoDespesa = codigoFavorecidoDespesa;
        return this;
    }

    /**
     * Get codigoFavorecidoDespesa
     *
     * @return codigoFavorecidoDespesa
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoFavorecidoDespesa() {
        return codigoFavorecidoDespesa;
    }

    public void setCodigoFavorecidoDespesa(String codigoFavorecidoDespesa) {
        this.codigoFavorecidoDespesa = codigoFavorecidoDespesa;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO codigoFavorecidoFinal(String codigoFavorecidoFinal) {
        this.codigoFavorecidoFinal = codigoFavorecidoFinal;
        return this;
    }

    /**
     * Get codigoFavorecidoFinal
     *
     * @return codigoFavorecidoFinal
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoFavorecidoFinal() {
        return codigoFavorecidoFinal;
    }

    public void setCodigoFavorecidoFinal(String codigoFavorecidoFinal) {
        this.codigoFavorecidoFinal = codigoFavorecidoFinal;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO codigoListaCredor(String codigoListaCredor) {
        this.codigoListaCredor = codigoListaCredor;
        return this;
    }

    /**
     * Get codigoListaCredor
     *
     * @return codigoListaCredor
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoListaCredor() {
        return codigoListaCredor;
    }

    public void setCodigoListaCredor(String codigoListaCredor) {
        this.codigoListaCredor = codigoListaCredor;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO codigoOrgaoSuperior(String codigoOrgaoSuperior) {
        this.codigoOrgaoSuperior = codigoOrgaoSuperior;
        return this;
    }

    /**
     * Get codigoOrgaoSuperior
     *
     * @return codigoOrgaoSuperior
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoOrgaoSuperior() {
        return codigoOrgaoSuperior;
    }

    public void setCodigoOrgaoSuperior(String codigoOrgaoSuperior) {
        this.codigoOrgaoSuperior = codigoOrgaoSuperior;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO codigoOrgaoVinculado(String codigoOrgaoVinculado) {
        this.codigoOrgaoVinculado = codigoOrgaoVinculado;
        return this;
    }

    /**
     * Get codigoOrgaoVinculado
     *
     * @return codigoOrgaoVinculado
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoOrgaoVinculado() {
        return codigoOrgaoVinculado;
    }

    public void setCodigoOrgaoVinculado(String codigoOrgaoVinculado) {
        this.codigoOrgaoVinculado = codigoOrgaoVinculado;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO codigoPagamento(String codigoPagamento) {
        this.codigoPagamento = codigoPagamento;
        return this;
    }

    /**
     * Get codigoPagamento
     *
     * @return codigoPagamento
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoPagamento() {
        return codigoPagamento;
    }

    public void setCodigoPagamento(String codigoPagamento) {
        this.codigoPagamento = codigoPagamento;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO codigoUnidadeGestora(String codigoUnidadeGestora) {
        this.codigoUnidadeGestora = codigoUnidadeGestora;
        return this;
    }

    /**
     * Get codigoUnidadeGestora
     *
     * @return codigoUnidadeGestora
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoUnidadeGestora() {
        return codigoUnidadeGestora;
    }

    public void setCodigoUnidadeGestora(String codigoUnidadeGestora) {
        this.codigoUnidadeGestora = codigoUnidadeGestora;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO dataCarga(String dataCarga) {
        this.dataCarga = dataCarga;
        return this;
    }

    /**
     * Get dataCarga
     *
     * @return dataCarga
     *
     */
    @ApiModelProperty(value = "")
    public String getDataCarga() {
        return dataCarga;
    }

    public void setDataCarga(String dataCarga) {
        this.dataCarga = dataCarga;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO municipioFavorecidoFinal(String municipioFavorecidoFinal) {
        this.municipioFavorecidoFinal = municipioFavorecidoFinal;
        return this;
    }

    /**
     * Get municipioFavorecidoFinal
     *
     * @return municipioFavorecidoFinal
     *
     */
    @ApiModelProperty(value = "")
    public String getMunicipioFavorecidoFinal() {
        return municipioFavorecidoFinal;
    }

    public void setMunicipioFavorecidoFinal(String municipioFavorecidoFinal) {
        this.municipioFavorecidoFinal = municipioFavorecidoFinal;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO nomeFavorecidoDespesa(String nomeFavorecidoDespesa) {
        this.nomeFavorecidoDespesa = nomeFavorecidoDespesa;
        return this;
    }

    /**
     * Get nomeFavorecidoDespesa
     *
     * @return nomeFavorecidoDespesa
     *
     */
    @ApiModelProperty(value = "")
    public String getNomeFavorecidoDespesa() {
        return nomeFavorecidoDespesa;
    }

    public void setNomeFavorecidoDespesa(String nomeFavorecidoDespesa) {
        this.nomeFavorecidoDespesa = nomeFavorecidoDespesa;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO nomeFavorecidoFinal(String nomeFavorecidoFinal) {
        this.nomeFavorecidoFinal = nomeFavorecidoFinal;
        return this;
    }

    /**
     * Get nomeFavorecidoFinal
     *
     * @return nomeFavorecidoFinal
     *
     */
    @ApiModelProperty(value = "")
    public String getNomeFavorecidoFinal() {
        return nomeFavorecidoFinal;
    }

    public void setNomeFavorecidoFinal(String nomeFavorecidoFinal) {
        this.nomeFavorecidoFinal = nomeFavorecidoFinal;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO orgaoSuperior(String orgaoSuperior) {
        this.orgaoSuperior = orgaoSuperior;
        return this;
    }

    /**
     * Get orgaoSuperior
     *
     * @return orgaoSuperior
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoSuperior() {
        return orgaoSuperior;
    }

    public void setOrgaoSuperior(String orgaoSuperior) {
        this.orgaoSuperior = orgaoSuperior;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO orgaoVinculado(String orgaoVinculado) {
        this.orgaoVinculado = orgaoVinculado;
        return this;
    }

    /**
     * Get orgaoVinculado
     *
     * @return orgaoVinculado
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoVinculado() {
        return orgaoVinculado;
    }

    public void setOrgaoVinculado(String orgaoVinculado) {
        this.orgaoVinculado = orgaoVinculado;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO skFatDW(Integer skFatDW) {
        this.skFatDW = skFatDW;
        return this;
    }

    /**
     * Get skFatDW
     *
     * @return skFatDW
     *
     */
    @ApiModelProperty(value = "")
    public Integer getSkFatDW() {
        return skFatDW;
    }

    public void setSkFatDW(Integer skFatDW) {
        this.skFatDW = skFatDW;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO skPessoaDespesa(Integer skPessoaDespesa) {
        this.skPessoaDespesa = skPessoaDespesa;
        return this;
    }

    /**
     * Get skPessoaDespesa
     *
     * @return skPessoaDespesa
     *
     */
    @ApiModelProperty(value = "")
    public Integer getSkPessoaDespesa() {
        return skPessoaDespesa;
    }

    public void setSkPessoaDespesa(Integer skPessoaDespesa) {
        this.skPessoaDespesa = skPessoaDespesa;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO skPessoaFinal(Integer skPessoaFinal) {
        this.skPessoaFinal = skPessoaFinal;
        return this;
    }

    /**
     * Get skPessoaFinal
     *
     * @return skPessoaFinal
     *
     */
    @ApiModelProperty(value = "")
    public Integer getSkPessoaFinal() {
        return skPessoaFinal;
    }

    public void setSkPessoaFinal(Integer skPessoaFinal) {
        this.skPessoaFinal = skPessoaFinal;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO tipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
        return this;
    }

    /**
     * Get tipoDocumento
     *
     * @return tipoDocumento
     *
     */
    @ApiModelProperty(value = "")
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO tipoFavorecidoDespesa(String tipoFavorecidoDespesa) {
        this.tipoFavorecidoDespesa = tipoFavorecidoDespesa;
        return this;
    }

    /**
     * Get tipoFavorecidoDespesa
     *
     * @return tipoFavorecidoDespesa
     *
     */
    @ApiModelProperty(value = "")
    public String getTipoFavorecidoDespesa() {
        return tipoFavorecidoDespesa;
    }

    public void setTipoFavorecidoDespesa(String tipoFavorecidoDespesa) {
        this.tipoFavorecidoDespesa = tipoFavorecidoDespesa;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO tipoFavorecidoFinal(String tipoFavorecidoFinal) {
        this.tipoFavorecidoFinal = tipoFavorecidoFinal;
        return this;
    }

    /**
     * Get tipoFavorecidoFinal
     *
     * @return tipoFavorecidoFinal
     *
     */
    @ApiModelProperty(value = "")
    public String getTipoFavorecidoFinal() {
        return tipoFavorecidoFinal;
    }

    public void setTipoFavorecidoFinal(String tipoFavorecidoFinal) {
        this.tipoFavorecidoFinal = tipoFavorecidoFinal;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO tipoOB(String tipoOB) {
        this.tipoOB = tipoOB;
        return this;
    }

    /**
     * Get tipoOB
     *
     * @return tipoOB
     *
     */
    @ApiModelProperty(value = "")
    public String getTipoOB() {
        return tipoOB;
    }

    public void setTipoOB(String tipoOB) {
        this.tipoOB = tipoOB;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO ufFavorecidoFinal(String ufFavorecidoFinal) {
        this.ufFavorecidoFinal = ufFavorecidoFinal;
        return this;
    }

    /**
     * Get ufFavorecidoFinal
     *
     * @return ufFavorecidoFinal
     *
     */
    @ApiModelProperty(value = "")
    public String getUfFavorecidoFinal() {
        return ufFavorecidoFinal;
    }

    public void setUfFavorecidoFinal(String ufFavorecidoFinal) {
        this.ufFavorecidoFinal = ufFavorecidoFinal;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO unidadeGestora(String unidadeGestora) {
        this.unidadeGestora = unidadeGestora;
        return this;
    }

    /**
     * Get unidadeGestora
     *
     * @return unidadeGestora
     *
     */
    @ApiModelProperty(value = "")
    public String getUnidadeGestora() {
        return unidadeGestora;
    }

    public void setUnidadeGestora(String unidadeGestora) {
        this.unidadeGestora = unidadeGestora;
    }

    public ConsultaFavorecidosFinaisPorDocumentoDTO valorFinal(String valorFinal) {
        this.valorFinal = valorFinal;
        return this;
    }

    /**
     * Get valorFinal
     *
     * @return valorFinal
     *
     */
    @ApiModelProperty(value = "")
    public String getValorFinal() {
        return valorFinal;
    }

    public void setValorFinal(String valorFinal) {
        this.valorFinal = valorFinal;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConsultaFavorecidosFinaisPorDocumentoDTO consultaFavorecidosFinaisPorDocumentoDTO = (ConsultaFavorecidosFinaisPorDocumentoDTO) o;
        return Objects.equals(this.codigoFavorecidoDespesa, consultaFavorecidosFinaisPorDocumentoDTO.codigoFavorecidoDespesa)
                && Objects.equals(this.codigoFavorecidoFinal, consultaFavorecidosFinaisPorDocumentoDTO.codigoFavorecidoFinal)
                && Objects.equals(this.codigoListaCredor, consultaFavorecidosFinaisPorDocumentoDTO.codigoListaCredor)
                && Objects.equals(this.codigoOrgaoSuperior, consultaFavorecidosFinaisPorDocumentoDTO.codigoOrgaoSuperior)
                && Objects.equals(this.codigoOrgaoVinculado, consultaFavorecidosFinaisPorDocumentoDTO.codigoOrgaoVinculado)
                && Objects.equals(this.codigoPagamento, consultaFavorecidosFinaisPorDocumentoDTO.codigoPagamento)
                && Objects.equals(this.codigoUnidadeGestora, consultaFavorecidosFinaisPorDocumentoDTO.codigoUnidadeGestora)
                && Objects.equals(this.dataCarga, consultaFavorecidosFinaisPorDocumentoDTO.dataCarga)
                && Objects.equals(this.municipioFavorecidoFinal, consultaFavorecidosFinaisPorDocumentoDTO.municipioFavorecidoFinal)
                && Objects.equals(this.nomeFavorecidoDespesa, consultaFavorecidosFinaisPorDocumentoDTO.nomeFavorecidoDespesa)
                && Objects.equals(this.nomeFavorecidoFinal, consultaFavorecidosFinaisPorDocumentoDTO.nomeFavorecidoFinal)
                && Objects.equals(this.orgaoSuperior, consultaFavorecidosFinaisPorDocumentoDTO.orgaoSuperior)
                && Objects.equals(this.orgaoVinculado, consultaFavorecidosFinaisPorDocumentoDTO.orgaoVinculado)
                && Objects.equals(this.skFatDW, consultaFavorecidosFinaisPorDocumentoDTO.skFatDW)
                && Objects.equals(this.skPessoaDespesa, consultaFavorecidosFinaisPorDocumentoDTO.skPessoaDespesa)
                && Objects.equals(this.skPessoaFinal, consultaFavorecidosFinaisPorDocumentoDTO.skPessoaFinal)
                && Objects.equals(this.tipoDocumento, consultaFavorecidosFinaisPorDocumentoDTO.tipoDocumento)
                && Objects.equals(this.tipoFavorecidoDespesa, consultaFavorecidosFinaisPorDocumentoDTO.tipoFavorecidoDespesa)
                && Objects.equals(this.tipoFavorecidoFinal, consultaFavorecidosFinaisPorDocumentoDTO.tipoFavorecidoFinal)
                && Objects.equals(this.tipoOB, consultaFavorecidosFinaisPorDocumentoDTO.tipoOB)
                && Objects.equals(this.ufFavorecidoFinal, consultaFavorecidosFinaisPorDocumentoDTO.ufFavorecidoFinal)
                && Objects.equals(this.unidadeGestora, consultaFavorecidosFinaisPorDocumentoDTO.unidadeGestora)
                && Objects.equals(this.valorFinal, consultaFavorecidosFinaisPorDocumentoDTO.valorFinal);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codigoFavorecidoDespesa, codigoFavorecidoFinal, codigoListaCredor, codigoOrgaoSuperior, codigoOrgaoVinculado, codigoPagamento, codigoUnidadeGestora, dataCarga, municipioFavorecidoFinal, nomeFavorecidoDespesa, nomeFavorecidoFinal, orgaoSuperior, orgaoVinculado, skFatDW, skPessoaDespesa, skPessoaFinal, tipoDocumento, tipoFavorecidoDespesa, tipoFavorecidoFinal, tipoOB, ufFavorecidoFinal, unidadeGestora, valorFinal);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ConsultaFavorecidosFinaisPorDocumentoDTO {\n");

        sb.append("    codigoFavorecidoDespesa: ").append(toIndentedString(codigoFavorecidoDespesa)).append("\n");
        sb.append("    codigoFavorecidoFinal: ").append(toIndentedString(codigoFavorecidoFinal)).append("\n");
        sb.append("    codigoListaCredor: ").append(toIndentedString(codigoListaCredor)).append("\n");
        sb.append("    codigoOrgaoSuperior: ").append(toIndentedString(codigoOrgaoSuperior)).append("\n");
        sb.append("    codigoOrgaoVinculado: ").append(toIndentedString(codigoOrgaoVinculado)).append("\n");
        sb.append("    codigoPagamento: ").append(toIndentedString(codigoPagamento)).append("\n");
        sb.append("    codigoUnidadeGestora: ").append(toIndentedString(codigoUnidadeGestora)).append("\n");
        sb.append("    dataCarga: ").append(toIndentedString(dataCarga)).append("\n");
        sb.append("    municipioFavorecidoFinal: ").append(toIndentedString(municipioFavorecidoFinal)).append("\n");
        sb.append("    nomeFavorecidoDespesa: ").append(toIndentedString(nomeFavorecidoDespesa)).append("\n");
        sb.append("    nomeFavorecidoFinal: ").append(toIndentedString(nomeFavorecidoFinal)).append("\n");
        sb.append("    orgaoSuperior: ").append(toIndentedString(orgaoSuperior)).append("\n");
        sb.append("    orgaoVinculado: ").append(toIndentedString(orgaoVinculado)).append("\n");
        sb.append("    skFatDW: ").append(toIndentedString(skFatDW)).append("\n");
        sb.append("    skPessoaDespesa: ").append(toIndentedString(skPessoaDespesa)).append("\n");
        sb.append("    skPessoaFinal: ").append(toIndentedString(skPessoaFinal)).append("\n");
        sb.append("    tipoDocumento: ").append(toIndentedString(tipoDocumento)).append("\n");
        sb.append("    tipoFavorecidoDespesa: ").append(toIndentedString(tipoFavorecidoDespesa)).append("\n");
        sb.append("    tipoFavorecidoFinal: ").append(toIndentedString(tipoFavorecidoFinal)).append("\n");
        sb.append("    tipoOB: ").append(toIndentedString(tipoOB)).append("\n");
        sb.append("    ufFavorecidoFinal: ").append(toIndentedString(ufFavorecidoFinal)).append("\n");
        sb.append("    unidadeGestora: ").append(toIndentedString(unidadeGestora)).append("\n");
        sb.append("    valorFinal: ").append(toIndentedString(valorFinal)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
