/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * ContratoDTO
 */
public class ContratoDTO {

    private CompraDTO compra = null;

    private String dataAssinatura = null;

    private String dataFimVigencia = null;

    private String dataInicioVigencia = null;

    private String dataPublicacaoDOU = null;

    private PessoaDTO fornecedor = null;

    private String fundamentoLegal = null;

    private Integer id = null;

    private String modalidadeCompra = null;

    private String numero = null;

    private String numeroProcesso = null;

    private String objeto = null;

    private String situacaoContrato = null;

    private UnidadeGestoraDTO unidadeGestora = null;

    private UnidadeGestoraDTO unidadeGestoraCompras = null;

    private BigDecimal valorFinalCompra = null;

    private BigDecimal valorInicialCompra = null;

    public ContratoDTO compra(CompraDTO compra) {
        this.compra = compra;
        return this;
    }

    /**
     * Get compra
     *
     * @return compra
     *
     */
    @ApiModelProperty(value = "")
    public CompraDTO getCompra() {
        return compra;
    }

    public void setCompra(CompraDTO compra) {
        this.compra = compra;
    }

    public ContratoDTO dataAssinatura(String dataAssinatura) {
        this.dataAssinatura = dataAssinatura;
        return this;
    }

    /**
     * Get dataAssinatura
     *
     * @return dataAssinatura
     *
     */
    @ApiModelProperty(value = "")
    public String getDataAssinatura() {
        return dataAssinatura;
    }

    public void setDataAssinatura(String dataAssinatura) {
        this.dataAssinatura = dataAssinatura;
    }

    public ContratoDTO dataFimVigencia(String dataFimVigencia) {
        this.dataFimVigencia = dataFimVigencia;
        return this;
    }

    /**
     * Get dataFimVigencia
     *
     * @return dataFimVigencia
     *
     */
    @ApiModelProperty(value = "")
    public String getDataFimVigencia() {
        return dataFimVigencia;
    }

    public void setDataFimVigencia(String dataFimVigencia) {
        this.dataFimVigencia = dataFimVigencia;
    }

    public ContratoDTO dataInicioVigencia(String dataInicioVigencia) {
        this.dataInicioVigencia = dataInicioVigencia;
        return this;
    }

    /**
     * Get dataInicioVigencia
     *
     * @return dataInicioVigencia
     *
     */
    @ApiModelProperty(value = "")
    public String getDataInicioVigencia() {
        return dataInicioVigencia;
    }

    public void setDataInicioVigencia(String dataInicioVigencia) {
        this.dataInicioVigencia = dataInicioVigencia;
    }

    public ContratoDTO dataPublicacaoDOU(String dataPublicacaoDOU) {
        this.dataPublicacaoDOU = dataPublicacaoDOU;
        return this;
    }

    /**
     * Get dataPublicacaoDOU
     *
     * @return dataPublicacaoDOU
     *
     */
    @ApiModelProperty(value = "")
    public String getDataPublicacaoDOU() {
        return dataPublicacaoDOU;
    }

    public void setDataPublicacaoDOU(String dataPublicacaoDOU) {
        this.dataPublicacaoDOU = dataPublicacaoDOU;
    }

    public ContratoDTO fornecedor(PessoaDTO fornecedor) {
        this.fornecedor = fornecedor;
        return this;
    }

    /**
     * Get fornecedor
     *
     * @return fornecedor
     *
     */
    @ApiModelProperty(value = "")
    public PessoaDTO getFornecedor() {
        return fornecedor;
    }

    public void setFornecedor(PessoaDTO fornecedor) {
        this.fornecedor = fornecedor;
    }

    public ContratoDTO fundamentoLegal(String fundamentoLegal) {
        this.fundamentoLegal = fundamentoLegal;
        return this;
    }

    /**
     * Get fundamentoLegal
     *
     * @return fundamentoLegal
     *
     */
    @ApiModelProperty(value = "")
    public String getFundamentoLegal() {
        return fundamentoLegal;
    }

    public void setFundamentoLegal(String fundamentoLegal) {
        this.fundamentoLegal = fundamentoLegal;
    }

    public ContratoDTO id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     *
     */
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ContratoDTO modalidadeCompra(String modalidadeCompra) {
        this.modalidadeCompra = modalidadeCompra;
        return this;
    }

    /**
     * Get modalidadeCompra
     *
     * @return modalidadeCompra
     *
     */
    @ApiModelProperty(value = "")
    public String getModalidadeCompra() {
        return modalidadeCompra;
    }

    public void setModalidadeCompra(String modalidadeCompra) {
        this.modalidadeCompra = modalidadeCompra;
    }

    public ContratoDTO numero(String numero) {
        this.numero = numero;
        return this;
    }

    /**
     * Get numero
     *
     * @return numero
     *
     */
    @ApiModelProperty(value = "")
    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public ContratoDTO numeroProcesso(String numeroProcesso) {
        this.numeroProcesso = numeroProcesso;
        return this;
    }

    /**
     * Get numeroProcesso
     *
     * @return numeroProcesso
     *
     */
    @ApiModelProperty(value = "")
    public String getNumeroProcesso() {
        return numeroProcesso;
    }

    public void setNumeroProcesso(String numeroProcesso) {
        this.numeroProcesso = numeroProcesso;
    }

    public ContratoDTO objeto(String objeto) {
        this.objeto = objeto;
        return this;
    }

    /**
     * Get objeto
     *
     * @return objeto
     *
     */
    @ApiModelProperty(value = "")
    public String getObjeto() {
        return objeto;
    }

    public void setObjeto(String objeto) {
        this.objeto = objeto;
    }

    public ContratoDTO situacaoContrato(String situacaoContrato) {
        this.situacaoContrato = situacaoContrato;
        return this;
    }

    /**
     * Get situacaoContrato
     *
     * @return situacaoContrato
     *
     */
    @ApiModelProperty(value = "")
    public String getSituacaoContrato() {
        return situacaoContrato;
    }

    public void setSituacaoContrato(String situacaoContrato) {
        this.situacaoContrato = situacaoContrato;
    }

    public ContratoDTO unidadeGestora(UnidadeGestoraDTO unidadeGestora) {
        this.unidadeGestora = unidadeGestora;
        return this;
    }

    /**
     * Get unidadeGestora
     *
     * @return unidadeGestora
     *
     */
    @ApiModelProperty(value = "")
    public UnidadeGestoraDTO getUnidadeGestora() {
        return unidadeGestora;
    }

    public void setUnidadeGestora(UnidadeGestoraDTO unidadeGestora) {
        this.unidadeGestora = unidadeGestora;
    }

    public ContratoDTO unidadeGestoraCompras(UnidadeGestoraDTO unidadeGestoraCompras) {
        this.unidadeGestoraCompras = unidadeGestoraCompras;
        return this;
    }

    /**
     * Get unidadeGestoraCompras
     *
     * @return unidadeGestoraCompras
     *
     */
    @ApiModelProperty(value = "")
    public UnidadeGestoraDTO getUnidadeGestoraCompras() {
        return unidadeGestoraCompras;
    }

    public void setUnidadeGestoraCompras(UnidadeGestoraDTO unidadeGestoraCompras) {
        this.unidadeGestoraCompras = unidadeGestoraCompras;
    }

    public ContratoDTO valorFinalCompra(BigDecimal valorFinalCompra) {
        this.valorFinalCompra = valorFinalCompra;
        return this;
    }

    /**
     * Get valorFinalCompra
     *
     * @return valorFinalCompra
     *
     */
    @ApiModelProperty(value = "")
    public BigDecimal getValorFinalCompra() {
        return valorFinalCompra;
    }

    public void setValorFinalCompra(BigDecimal valorFinalCompra) {
        this.valorFinalCompra = valorFinalCompra;
    }

    public ContratoDTO valorInicialCompra(BigDecimal valorInicialCompra) {
        this.valorInicialCompra = valorInicialCompra;
        return this;
    }

    /**
     * Get valorInicialCompra
     *
     * @return valorInicialCompra
     *
     */
    @ApiModelProperty(value = "")
    public BigDecimal getValorInicialCompra() {
        return valorInicialCompra;
    }

    public void setValorInicialCompra(BigDecimal valorInicialCompra) {
        this.valorInicialCompra = valorInicialCompra;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContratoDTO contratoDTO = (ContratoDTO) o;
        return Objects.equals(this.compra, contratoDTO.compra)
                && Objects.equals(this.dataAssinatura, contratoDTO.dataAssinatura)
                && Objects.equals(this.dataFimVigencia, contratoDTO.dataFimVigencia)
                && Objects.equals(this.dataInicioVigencia, contratoDTO.dataInicioVigencia)
                && Objects.equals(this.dataPublicacaoDOU, contratoDTO.dataPublicacaoDOU)
                && Objects.equals(this.fornecedor, contratoDTO.fornecedor)
                && Objects.equals(this.fundamentoLegal, contratoDTO.fundamentoLegal)
                && Objects.equals(this.id, contratoDTO.id)
                && Objects.equals(this.modalidadeCompra, contratoDTO.modalidadeCompra)
                && Objects.equals(this.numero, contratoDTO.numero)
                && Objects.equals(this.numeroProcesso, contratoDTO.numeroProcesso)
                && Objects.equals(this.objeto, contratoDTO.objeto)
                && Objects.equals(this.situacaoContrato, contratoDTO.situacaoContrato)
                && Objects.equals(this.unidadeGestora, contratoDTO.unidadeGestora)
                && Objects.equals(this.unidadeGestoraCompras, contratoDTO.unidadeGestoraCompras)
                && Objects.equals(this.valorFinalCompra, contratoDTO.valorFinalCompra)
                && Objects.equals(this.valorInicialCompra, contratoDTO.valorInicialCompra);
    }

    @Override
    public int hashCode() {
        return Objects.hash(compra, dataAssinatura, dataFimVigencia, dataInicioVigencia, dataPublicacaoDOU, fornecedor, fundamentoLegal, id, modalidadeCompra, numero, numeroProcesso, objeto, situacaoContrato, unidadeGestora, unidadeGestoraCompras, valorFinalCompra, valorInicialCompra);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ContratoDTO {\n");

        sb.append("    compra: ").append(toIndentedString(compra)).append("\n");
        sb.append("    dataAssinatura: ").append(toIndentedString(dataAssinatura)).append("\n");
        sb.append("    dataFimVigencia: ").append(toIndentedString(dataFimVigencia)).append("\n");
        sb.append("    dataInicioVigencia: ").append(toIndentedString(dataInicioVigencia)).append("\n");
        sb.append("    dataPublicacaoDOU: ").append(toIndentedString(dataPublicacaoDOU)).append("\n");
        sb.append("    fornecedor: ").append(toIndentedString(fornecedor)).append("\n");
        sb.append("    fundamentoLegal: ").append(toIndentedString(fundamentoLegal)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    modalidadeCompra: ").append(toIndentedString(modalidadeCompra)).append("\n");
        sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
        sb.append("    numeroProcesso: ").append(toIndentedString(numeroProcesso)).append("\n");
        sb.append("    objeto: ").append(toIndentedString(objeto)).append("\n");
        sb.append("    situacaoContrato: ").append(toIndentedString(situacaoContrato)).append("\n");
        sb.append("    unidadeGestora: ").append(toIndentedString(unidadeGestora)).append("\n");
        sb.append("    unidadeGestoraCompras: ").append(toIndentedString(unidadeGestoraCompras)).append("\n");
        sb.append("    valorFinalCompra: ").append(toIndentedString(valorFinalCompra)).append("\n");
        sb.append("    valorInicialCompra: ").append(toIndentedString(valorInicialCompra)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
