/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * DespesaAnualPorOrgaoDTO
 */
public class DespesaAnualPorOrgaoDTO {

    private Integer ano = null;

    private String codigoOrgao = null;

    private String codigoOrgaoSuperior = null;

    private String empenhado = null;

    private String liquidado = null;

    private String orgao = null;

    private String orgaoSuperior = null;

    private String pago = null;

    public DespesaAnualPorOrgaoDTO ano(Integer ano) {
        this.ano = ano;
        return this;
    }

    /**
     * Get ano
     *
     * @return ano
     *
     */
    @ApiModelProperty(value = "")
    public Integer getAno() {
        return ano;
    }

    public void setAno(Integer ano) {
        this.ano = ano;
    }

    public DespesaAnualPorOrgaoDTO codigoOrgao(String codigoOrgao) {
        this.codigoOrgao = codigoOrgao;
        return this;
    }

    /**
     * Get codigoOrgao
     *
     * @return codigoOrgao
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoOrgao() {
        return codigoOrgao;
    }

    public void setCodigoOrgao(String codigoOrgao) {
        this.codigoOrgao = codigoOrgao;
    }

    public DespesaAnualPorOrgaoDTO codigoOrgaoSuperior(String codigoOrgaoSuperior) {
        this.codigoOrgaoSuperior = codigoOrgaoSuperior;
        return this;
    }

    /**
     * Get codigoOrgaoSuperior
     *
     * @return codigoOrgaoSuperior
     *
     */
    @ApiModelProperty(value = "")
    public String getCodigoOrgaoSuperior() {
        return codigoOrgaoSuperior;
    }

    public void setCodigoOrgaoSuperior(String codigoOrgaoSuperior) {
        this.codigoOrgaoSuperior = codigoOrgaoSuperior;
    }

    public DespesaAnualPorOrgaoDTO empenhado(String empenhado) {
        this.empenhado = empenhado;
        return this;
    }

    /**
     * Get empenhado
     *
     * @return empenhado
     *
     */
    @ApiModelProperty(value = "")
    public String getEmpenhado() {
        return empenhado;
    }

    public void setEmpenhado(String empenhado) {
        this.empenhado = empenhado;
    }

    public DespesaAnualPorOrgaoDTO liquidado(String liquidado) {
        this.liquidado = liquidado;
        return this;
    }

    /**
     * Get liquidado
     *
     * @return liquidado
     *
     */
    @ApiModelProperty(value = "")
    public String getLiquidado() {
        return liquidado;
    }

    public void setLiquidado(String liquidado) {
        this.liquidado = liquidado;
    }

    public DespesaAnualPorOrgaoDTO orgao(String orgao) {
        this.orgao = orgao;
        return this;
    }

    /**
     * Get orgao
     *
     * @return orgao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgao() {
        return orgao;
    }

    public void setOrgao(String orgao) {
        this.orgao = orgao;
    }

    public DespesaAnualPorOrgaoDTO orgaoSuperior(String orgaoSuperior) {
        this.orgaoSuperior = orgaoSuperior;
        return this;
    }

    /**
     * Get orgaoSuperior
     *
     * @return orgaoSuperior
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoSuperior() {
        return orgaoSuperior;
    }

    public void setOrgaoSuperior(String orgaoSuperior) {
        this.orgaoSuperior = orgaoSuperior;
    }

    public DespesaAnualPorOrgaoDTO pago(String pago) {
        this.pago = pago;
        return this;
    }

    /**
     * Get pago
     *
     * @return pago
     *
     */
    @ApiModelProperty(value = "")
    public String getPago() {
        return pago;
    }

    public void setPago(String pago) {
        this.pago = pago;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DespesaAnualPorOrgaoDTO despesaAnualPorOrgaoDTO = (DespesaAnualPorOrgaoDTO) o;
        return Objects.equals(this.ano, despesaAnualPorOrgaoDTO.ano)
                && Objects.equals(this.codigoOrgao, despesaAnualPorOrgaoDTO.codigoOrgao)
                && Objects.equals(this.codigoOrgaoSuperior, despesaAnualPorOrgaoDTO.codigoOrgaoSuperior)
                && Objects.equals(this.empenhado, despesaAnualPorOrgaoDTO.empenhado)
                && Objects.equals(this.liquidado, despesaAnualPorOrgaoDTO.liquidado)
                && Objects.equals(this.orgao, despesaAnualPorOrgaoDTO.orgao)
                && Objects.equals(this.orgaoSuperior, despesaAnualPorOrgaoDTO.orgaoSuperior)
                && Objects.equals(this.pago, despesaAnualPorOrgaoDTO.pago);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ano, codigoOrgao, codigoOrgaoSuperior, empenhado, liquidado, orgao, orgaoSuperior, pago);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DespesaAnualPorOrgaoDTO {\n");

        sb.append("    ano: ").append(toIndentedString(ano)).append("\n");
        sb.append("    codigoOrgao: ").append(toIndentedString(codigoOrgao)).append("\n");
        sb.append("    codigoOrgaoSuperior: ").append(toIndentedString(codigoOrgaoSuperior)).append("\n");
        sb.append("    empenhado: ").append(toIndentedString(empenhado)).append("\n");
        sb.append("    liquidado: ").append(toIndentedString(liquidado)).append("\n");
        sb.append("    orgao: ").append(toIndentedString(orgao)).append("\n");
        sb.append("    orgaoSuperior: ").append(toIndentedString(orgaoSuperior)).append("\n");
        sb.append("    pago: ").append(toIndentedString(pago)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
