/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * DespesasPorDocumentoDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-08-10T02:15:55.020Z")
public class DespesasPorDocumentoDTO {
  @SerializedName("acao")
  private String acao = null;

  @SerializedName("autor")
  private String autor = null;

  @SerializedName("categoria")
  private String categoria = null;

  @SerializedName("codigoFavorecido")
  private String codigoFavorecido = null;

  @SerializedName("codigoOrgao")
  private String codigoOrgao = null;

  @SerializedName("codigoOrgaoSuperior")
  private String codigoOrgaoSuperior = null;

  @SerializedName("codigoUg")
  private String codigoUg = null;

  @SerializedName("codigoUo")
  private String codigoUo = null;

  @SerializedName("data")
  private String data = null;

  @SerializedName("documento")
  private String documento = null;

  @SerializedName("documentoResumido")
  private String documentoResumido = null;

  @SerializedName("elemento")
  private String elemento = null;

  @SerializedName("especie")
  private String especie = null;

  @SerializedName("fase")
  private String fase = null;

  @SerializedName("favorecido")
  private String favorecido = null;

  @SerializedName("favorecidoIntermediario")
  private Boolean favorecidoIntermediario = null;

  @SerializedName("favorecidoListaFaturas")
  private Boolean favorecidoListaFaturas = null;

  @SerializedName("funcao")
  private String funcao = null;

  @SerializedName("grupo")
  private String grupo = null;

  @SerializedName("localizadorGasto")
  private String localizadorGasto = null;

  @SerializedName("modalidade")
  private String modalidade = null;

  @SerializedName("nomeFavorecido")
  private String nomeFavorecido = null;

  @SerializedName("numeroProcesso")
  private String numeroProcesso = null;

  @SerializedName("observacao")
  private String observacao = null;

  @SerializedName("orgao")
  private String orgao = null;

  @SerializedName("orgaoSuperior")
  private String orgaoSuperior = null;

  @SerializedName("planoOrcamentario")
  private String planoOrcamentario = null;

  @SerializedName("programa")
  private String programa = null;

  @SerializedName("subTitulo")
  private String subTitulo = null;

  @SerializedName("subfuncao")
  private String subfuncao = null;

  @SerializedName("ufFavorecido")
  private String ufFavorecido = null;

  @SerializedName("ug")
  private String ug = null;

  @SerializedName("uo")
  private String uo = null;

  @SerializedName("valor")
  private String valor = null;

  public DespesasPorDocumentoDTO acao(String acao) {
    this.acao = acao;
    return this;
  }

   /**
   * Get acao
   * @return acao
  **/
  @ApiModelProperty(value = "")
  public String getAcao() {
    return acao;
  }

  public void setAcao(String acao) {
    this.acao = acao;
  }

  public DespesasPorDocumentoDTO autor(String autor) {
    this.autor = autor;
    return this;
  }

   /**
   * Get autor
   * @return autor
  **/
  @ApiModelProperty(value = "")
  public String getAutor() {
    return autor;
  }

  public void setAutor(String autor) {
    this.autor = autor;
  }

  public DespesasPorDocumentoDTO categoria(String categoria) {
    this.categoria = categoria;
    return this;
  }

   /**
   * Get categoria
   * @return categoria
  **/
  @ApiModelProperty(value = "")
  public String getCategoria() {
    return categoria;
  }

  public void setCategoria(String categoria) {
    this.categoria = categoria;
  }

  public DespesasPorDocumentoDTO codigoFavorecido(String codigoFavorecido) {
    this.codigoFavorecido = codigoFavorecido;
    return this;
  }

   /**
   * Get codigoFavorecido
   * @return codigoFavorecido
  **/
  @ApiModelProperty(value = "")
  public String getCodigoFavorecido() {
    return codigoFavorecido;
  }

  public void setCodigoFavorecido(String codigoFavorecido) {
    this.codigoFavorecido = codigoFavorecido;
  }

  public DespesasPorDocumentoDTO codigoOrgao(String codigoOrgao) {
    this.codigoOrgao = codigoOrgao;
    return this;
  }

   /**
   * Get codigoOrgao
   * @return codigoOrgao
  **/
  @ApiModelProperty(value = "")
  public String getCodigoOrgao() {
    return codigoOrgao;
  }

  public void setCodigoOrgao(String codigoOrgao) {
    this.codigoOrgao = codigoOrgao;
  }

  public DespesasPorDocumentoDTO codigoOrgaoSuperior(String codigoOrgaoSuperior) {
    this.codigoOrgaoSuperior = codigoOrgaoSuperior;
    return this;
  }

   /**
   * Get codigoOrgaoSuperior
   * @return codigoOrgaoSuperior
  **/
  @ApiModelProperty(value = "")
  public String getCodigoOrgaoSuperior() {
    return codigoOrgaoSuperior;
  }

  public void setCodigoOrgaoSuperior(String codigoOrgaoSuperior) {
    this.codigoOrgaoSuperior = codigoOrgaoSuperior;
  }

  public DespesasPorDocumentoDTO codigoUg(String codigoUg) {
    this.codigoUg = codigoUg;
    return this;
  }

   /**
   * Get codigoUg
   * @return codigoUg
  **/
  @ApiModelProperty(value = "")
  public String getCodigoUg() {
    return codigoUg;
  }

  public void setCodigoUg(String codigoUg) {
    this.codigoUg = codigoUg;
  }

  public DespesasPorDocumentoDTO codigoUo(String codigoUo) {
    this.codigoUo = codigoUo;
    return this;
  }

   /**
   * Get codigoUo
   * @return codigoUo
  **/
  @ApiModelProperty(value = "")
  public String getCodigoUo() {
    return codigoUo;
  }

  public void setCodigoUo(String codigoUo) {
    this.codigoUo = codigoUo;
  }

  public DespesasPorDocumentoDTO data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public DespesasPorDocumentoDTO documento(String documento) {
    this.documento = documento;
    return this;
  }

   /**
   * Get documento
   * @return documento
  **/
  @ApiModelProperty(value = "")
  public String getDocumento() {
    return documento;
  }

  public void setDocumento(String documento) {
    this.documento = documento;
  }

  public DespesasPorDocumentoDTO documentoResumido(String documentoResumido) {
    this.documentoResumido = documentoResumido;
    return this;
  }

   /**
   * Get documentoResumido
   * @return documentoResumido
  **/
  @ApiModelProperty(value = "")
  public String getDocumentoResumido() {
    return documentoResumido;
  }

  public void setDocumentoResumido(String documentoResumido) {
    this.documentoResumido = documentoResumido;
  }

  public DespesasPorDocumentoDTO elemento(String elemento) {
    this.elemento = elemento;
    return this;
  }

   /**
   * Get elemento
   * @return elemento
  **/
  @ApiModelProperty(value = "")
  public String getElemento() {
    return elemento;
  }

  public void setElemento(String elemento) {
    this.elemento = elemento;
  }

  public DespesasPorDocumentoDTO especie(String especie) {
    this.especie = especie;
    return this;
  }

   /**
   * Get especie
   * @return especie
  **/
  @ApiModelProperty(value = "")
  public String getEspecie() {
    return especie;
  }

  public void setEspecie(String especie) {
    this.especie = especie;
  }

  public DespesasPorDocumentoDTO fase(String fase) {
    this.fase = fase;
    return this;
  }

   /**
   * Get fase
   * @return fase
  **/
  @ApiModelProperty(value = "")
  public String getFase() {
    return fase;
  }

  public void setFase(String fase) {
    this.fase = fase;
  }

  public DespesasPorDocumentoDTO favorecido(String favorecido) {
    this.favorecido = favorecido;
    return this;
  }

   /**
   * Get favorecido
   * @return favorecido
  **/
  @ApiModelProperty(value = "")
  public String getFavorecido() {
    return favorecido;
  }

  public void setFavorecido(String favorecido) {
    this.favorecido = favorecido;
  }

  public DespesasPorDocumentoDTO favorecidoIntermediario(Boolean favorecidoIntermediario) {
    this.favorecidoIntermediario = favorecidoIntermediario;
    return this;
  }

   /**
   * Get favorecidoIntermediario
   * @return favorecidoIntermediario
  **/
  @ApiModelProperty(value = "")
  public Boolean isFavorecidoIntermediario() {
    return favorecidoIntermediario;
  }

  public void setFavorecidoIntermediario(Boolean favorecidoIntermediario) {
    this.favorecidoIntermediario = favorecidoIntermediario;
  }

  public DespesasPorDocumentoDTO favorecidoListaFaturas(Boolean favorecidoListaFaturas) {
    this.favorecidoListaFaturas = favorecidoListaFaturas;
    return this;
  }

   /**
   * Get favorecidoListaFaturas
   * @return favorecidoListaFaturas
  **/
  @ApiModelProperty(value = "")
  public Boolean isFavorecidoListaFaturas() {
    return favorecidoListaFaturas;
  }

  public void setFavorecidoListaFaturas(Boolean favorecidoListaFaturas) {
    this.favorecidoListaFaturas = favorecidoListaFaturas;
  }

  public DespesasPorDocumentoDTO funcao(String funcao) {
    this.funcao = funcao;
    return this;
  }

   /**
   * Get funcao
   * @return funcao
  **/
  @ApiModelProperty(value = "")
  public String getFuncao() {
    return funcao;
  }

  public void setFuncao(String funcao) {
    this.funcao = funcao;
  }

  public DespesasPorDocumentoDTO grupo(String grupo) {
    this.grupo = grupo;
    return this;
  }

   /**
   * Get grupo
   * @return grupo
  **/
  @ApiModelProperty(value = "")
  public String getGrupo() {
    return grupo;
  }

  public void setGrupo(String grupo) {
    this.grupo = grupo;
  }

  public DespesasPorDocumentoDTO localizadorGasto(String localizadorGasto) {
    this.localizadorGasto = localizadorGasto;
    return this;
  }

   /**
   * Get localizadorGasto
   * @return localizadorGasto
  **/
  @ApiModelProperty(value = "")
  public String getLocalizadorGasto() {
    return localizadorGasto;
  }

  public void setLocalizadorGasto(String localizadorGasto) {
    this.localizadorGasto = localizadorGasto;
  }

  public DespesasPorDocumentoDTO modalidade(String modalidade) {
    this.modalidade = modalidade;
    return this;
  }

   /**
   * Get modalidade
   * @return modalidade
  **/
  @ApiModelProperty(value = "")
  public String getModalidade() {
    return modalidade;
  }

  public void setModalidade(String modalidade) {
    this.modalidade = modalidade;
  }

  public DespesasPorDocumentoDTO nomeFavorecido(String nomeFavorecido) {
    this.nomeFavorecido = nomeFavorecido;
    return this;
  }

   /**
   * Get nomeFavorecido
   * @return nomeFavorecido
  **/
  @ApiModelProperty(value = "")
  public String getNomeFavorecido() {
    return nomeFavorecido;
  }

  public void setNomeFavorecido(String nomeFavorecido) {
    this.nomeFavorecido = nomeFavorecido;
  }

  public DespesasPorDocumentoDTO numeroProcesso(String numeroProcesso) {
    this.numeroProcesso = numeroProcesso;
    return this;
  }

   /**
   * Get numeroProcesso
   * @return numeroProcesso
  **/
  @ApiModelProperty(value = "")
  public String getNumeroProcesso() {
    return numeroProcesso;
  }

  public void setNumeroProcesso(String numeroProcesso) {
    this.numeroProcesso = numeroProcesso;
  }

  public DespesasPorDocumentoDTO observacao(String observacao) {
    this.observacao = observacao;
    return this;
  }

   /**
   * Get observacao
   * @return observacao
  **/
  @ApiModelProperty(value = "")
  public String getObservacao() {
    return observacao;
  }

  public void setObservacao(String observacao) {
    this.observacao = observacao;
  }

  public DespesasPorDocumentoDTO orgao(String orgao) {
    this.orgao = orgao;
    return this;
  }

   /**
   * Get orgao
   * @return orgao
  **/
  @ApiModelProperty(value = "")
  public String getOrgao() {
    return orgao;
  }

  public void setOrgao(String orgao) {
    this.orgao = orgao;
  }

  public DespesasPorDocumentoDTO orgaoSuperior(String orgaoSuperior) {
    this.orgaoSuperior = orgaoSuperior;
    return this;
  }

   /**
   * Get orgaoSuperior
   * @return orgaoSuperior
  **/
  @ApiModelProperty(value = "")
  public String getOrgaoSuperior() {
    return orgaoSuperior;
  }

  public void setOrgaoSuperior(String orgaoSuperior) {
    this.orgaoSuperior = orgaoSuperior;
  }

  public DespesasPorDocumentoDTO planoOrcamentario(String planoOrcamentario) {
    this.planoOrcamentario = planoOrcamentario;
    return this;
  }

   /**
   * Get planoOrcamentario
   * @return planoOrcamentario
  **/
  @ApiModelProperty(value = "")
  public String getPlanoOrcamentario() {
    return planoOrcamentario;
  }

  public void setPlanoOrcamentario(String planoOrcamentario) {
    this.planoOrcamentario = planoOrcamentario;
  }

  public DespesasPorDocumentoDTO programa(String programa) {
    this.programa = programa;
    return this;
  }

   /**
   * Get programa
   * @return programa
  **/
  @ApiModelProperty(value = "")
  public String getPrograma() {
    return programa;
  }

  public void setPrograma(String programa) {
    this.programa = programa;
  }

  public DespesasPorDocumentoDTO subTitulo(String subTitulo) {
    this.subTitulo = subTitulo;
    return this;
  }

   /**
   * Get subTitulo
   * @return subTitulo
  **/
  @ApiModelProperty(value = "")
  public String getSubTitulo() {
    return subTitulo;
  }

  public void setSubTitulo(String subTitulo) {
    this.subTitulo = subTitulo;
  }

  public DespesasPorDocumentoDTO subfuncao(String subfuncao) {
    this.subfuncao = subfuncao;
    return this;
  }

   /**
   * Get subfuncao
   * @return subfuncao
  **/
  @ApiModelProperty(value = "")
  public String getSubfuncao() {
    return subfuncao;
  }

  public void setSubfuncao(String subfuncao) {
    this.subfuncao = subfuncao;
  }

  public DespesasPorDocumentoDTO ufFavorecido(String ufFavorecido) {
    this.ufFavorecido = ufFavorecido;
    return this;
  }

   /**
   * Get ufFavorecido
   * @return ufFavorecido
  **/
  @ApiModelProperty(value = "")
  public String getUfFavorecido() {
    return ufFavorecido;
  }

  public void setUfFavorecido(String ufFavorecido) {
    this.ufFavorecido = ufFavorecido;
  }

  public DespesasPorDocumentoDTO ug(String ug) {
    this.ug = ug;
    return this;
  }

   /**
   * Get ug
   * @return ug
  **/
  @ApiModelProperty(value = "")
  public String getUg() {
    return ug;
  }

  public void setUg(String ug) {
    this.ug = ug;
  }

  public DespesasPorDocumentoDTO uo(String uo) {
    this.uo = uo;
    return this;
  }

   /**
   * Get uo
   * @return uo
  **/
  @ApiModelProperty(value = "")
  public String getUo() {
    return uo;
  }

  public void setUo(String uo) {
    this.uo = uo;
  }

  public DespesasPorDocumentoDTO valor(String valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Get valor
   * @return valor
  **/
  @ApiModelProperty(value = "")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DespesasPorDocumentoDTO despesasPorDocumentoDTO = (DespesasPorDocumentoDTO) o;
    return Objects.equals(this.acao, despesasPorDocumentoDTO.acao) &&
        Objects.equals(this.autor, despesasPorDocumentoDTO.autor) &&
        Objects.equals(this.categoria, despesasPorDocumentoDTO.categoria) &&
        Objects.equals(this.codigoFavorecido, despesasPorDocumentoDTO.codigoFavorecido) &&
        Objects.equals(this.codigoOrgao, despesasPorDocumentoDTO.codigoOrgao) &&
        Objects.equals(this.codigoOrgaoSuperior, despesasPorDocumentoDTO.codigoOrgaoSuperior) &&
        Objects.equals(this.codigoUg, despesasPorDocumentoDTO.codigoUg) &&
        Objects.equals(this.codigoUo, despesasPorDocumentoDTO.codigoUo) &&
        Objects.equals(this.data, despesasPorDocumentoDTO.data) &&
        Objects.equals(this.documento, despesasPorDocumentoDTO.documento) &&
        Objects.equals(this.documentoResumido, despesasPorDocumentoDTO.documentoResumido) &&
        Objects.equals(this.elemento, despesasPorDocumentoDTO.elemento) &&
        Objects.equals(this.especie, despesasPorDocumentoDTO.especie) &&
        Objects.equals(this.fase, despesasPorDocumentoDTO.fase) &&
        Objects.equals(this.favorecido, despesasPorDocumentoDTO.favorecido) &&
        Objects.equals(this.favorecidoIntermediario, despesasPorDocumentoDTO.favorecidoIntermediario) &&
        Objects.equals(this.favorecidoListaFaturas, despesasPorDocumentoDTO.favorecidoListaFaturas) &&
        Objects.equals(this.funcao, despesasPorDocumentoDTO.funcao) &&
        Objects.equals(this.grupo, despesasPorDocumentoDTO.grupo) &&
        Objects.equals(this.localizadorGasto, despesasPorDocumentoDTO.localizadorGasto) &&
        Objects.equals(this.modalidade, despesasPorDocumentoDTO.modalidade) &&
        Objects.equals(this.nomeFavorecido, despesasPorDocumentoDTO.nomeFavorecido) &&
        Objects.equals(this.numeroProcesso, despesasPorDocumentoDTO.numeroProcesso) &&
        Objects.equals(this.observacao, despesasPorDocumentoDTO.observacao) &&
        Objects.equals(this.orgao, despesasPorDocumentoDTO.orgao) &&
        Objects.equals(this.orgaoSuperior, despesasPorDocumentoDTO.orgaoSuperior) &&
        Objects.equals(this.planoOrcamentario, despesasPorDocumentoDTO.planoOrcamentario) &&
        Objects.equals(this.programa, despesasPorDocumentoDTO.programa) &&
        Objects.equals(this.subTitulo, despesasPorDocumentoDTO.subTitulo) &&
        Objects.equals(this.subfuncao, despesasPorDocumentoDTO.subfuncao) &&
        Objects.equals(this.ufFavorecido, despesasPorDocumentoDTO.ufFavorecido) &&
        Objects.equals(this.ug, despesasPorDocumentoDTO.ug) &&
        Objects.equals(this.uo, despesasPorDocumentoDTO.uo) &&
        Objects.equals(this.valor, despesasPorDocumentoDTO.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acao, autor, categoria, codigoFavorecido, codigoOrgao, codigoOrgaoSuperior, codigoUg, codigoUo, data, documento, documentoResumido, elemento, especie, fase, favorecido, favorecidoIntermediario, favorecidoListaFaturas, funcao, grupo, localizadorGasto, modalidade, nomeFavorecido, numeroProcesso, observacao, orgao, orgaoSuperior, planoOrcamentario, programa, subTitulo, subfuncao, ufFavorecido, ug, uo, valor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DespesasPorDocumentoDTO {\n");
    
    sb.append("    acao: ").append(toIndentedString(acao)).append("\n");
    sb.append("    autor: ").append(toIndentedString(autor)).append("\n");
    sb.append("    categoria: ").append(toIndentedString(categoria)).append("\n");
    sb.append("    codigoFavorecido: ").append(toIndentedString(codigoFavorecido)).append("\n");
    sb.append("    codigoOrgao: ").append(toIndentedString(codigoOrgao)).append("\n");
    sb.append("    codigoOrgaoSuperior: ").append(toIndentedString(codigoOrgaoSuperior)).append("\n");
    sb.append("    codigoUg: ").append(toIndentedString(codigoUg)).append("\n");
    sb.append("    codigoUo: ").append(toIndentedString(codigoUo)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    documento: ").append(toIndentedString(documento)).append("\n");
    sb.append("    documentoResumido: ").append(toIndentedString(documentoResumido)).append("\n");
    sb.append("    elemento: ").append(toIndentedString(elemento)).append("\n");
    sb.append("    especie: ").append(toIndentedString(especie)).append("\n");
    sb.append("    fase: ").append(toIndentedString(fase)).append("\n");
    sb.append("    favorecido: ").append(toIndentedString(favorecido)).append("\n");
    sb.append("    favorecidoIntermediario: ").append(toIndentedString(favorecidoIntermediario)).append("\n");
    sb.append("    favorecidoListaFaturas: ").append(toIndentedString(favorecidoListaFaturas)).append("\n");
    sb.append("    funcao: ").append(toIndentedString(funcao)).append("\n");
    sb.append("    grupo: ").append(toIndentedString(grupo)).append("\n");
    sb.append("    localizadorGasto: ").append(toIndentedString(localizadorGasto)).append("\n");
    sb.append("    modalidade: ").append(toIndentedString(modalidade)).append("\n");
    sb.append("    nomeFavorecido: ").append(toIndentedString(nomeFavorecido)).append("\n");
    sb.append("    numeroProcesso: ").append(toIndentedString(numeroProcesso)).append("\n");
    sb.append("    observacao: ").append(toIndentedString(observacao)).append("\n");
    sb.append("    orgao: ").append(toIndentedString(orgao)).append("\n");
    sb.append("    orgaoSuperior: ").append(toIndentedString(orgaoSuperior)).append("\n");
    sb.append("    planoOrcamentario: ").append(toIndentedString(planoOrcamentario)).append("\n");
    sb.append("    programa: ").append(toIndentedString(programa)).append("\n");
    sb.append("    subTitulo: ").append(toIndentedString(subTitulo)).append("\n");
    sb.append("    subfuncao: ").append(toIndentedString(subfuncao)).append("\n");
    sb.append("    ufFavorecido: ").append(toIndentedString(ufFavorecido)).append("\n");
    sb.append("    ug: ").append(toIndentedString(ug)).append("\n");
    sb.append("    uo: ").append(toIndentedString(uo)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
