/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * FichaFuncaoDTO
 */
public class FichaFuncaoDTO {

    private List<String> afastamentos = null;

    private String atividade = null;

    private String cpfDescaracterizado = null;

    private String dataIngressoFuncao = null;

    private String dataIngressoOrgao = null;

    private String dataIngressoServicoPublico = null;

    private String dataPublicacaoDocumentoIngressoServicoPublico = null;

    private String diplomaLegal = null;

    private String funcao = null;

    private String jornadaTrabalho = null;

    private String matriculaDescaracterizada = null;

    private String nome = null;

    private String opcaoFuncao = null;

    private String orgaoExercicio = null;

    private String orgaoLotacao = null;

    private String orgaoServidorExercicio = null;

    private String orgaoServidorLotacao = null;

    private String orgaoSuperiorExercicio = null;

    private String orgaoSuperiorLotacao = null;

    private String regimeJuridico = null;

    private String situacaoServidor = null;

    private String ufExercicio = null;

    private String uorgExercicio = null;

    private String uorgLotacao = null;

    public FichaFuncaoDTO afastamentos(List<String> afastamentos) {
        this.afastamentos = afastamentos;
        return this;
    }

    public FichaFuncaoDTO addAfastamentosItem(String afastamentosItem) {
        if (this.afastamentos == null) {
            this.afastamentos = new ArrayList<String>();
        }
        this.afastamentos.add(afastamentosItem);
        return this;
    }

    /**
     * Get afastamentos
     *
     * @return afastamentos
     *
     */
    @ApiModelProperty(value = "")
    public List<String> getAfastamentos() {
        return afastamentos;
    }

    public void setAfastamentos(List<String> afastamentos) {
        this.afastamentos = afastamentos;
    }

    public FichaFuncaoDTO atividade(String atividade) {
        this.atividade = atividade;
        return this;
    }

    /**
     * Get atividade
     *
     * @return atividade
     *
     */
    @ApiModelProperty(value = "")
    public String getAtividade() {
        return atividade;
    }

    public void setAtividade(String atividade) {
        this.atividade = atividade;
    }

    public FichaFuncaoDTO cpfDescaracterizado(String cpfDescaracterizado) {
        this.cpfDescaracterizado = cpfDescaracterizado;
        return this;
    }

    /**
     * Get cpfDescaracterizado
     *
     * @return cpfDescaracterizado
     *
     */
    @ApiModelProperty(value = "")
    public String getCpfDescaracterizado() {
        return cpfDescaracterizado;
    }

    public void setCpfDescaracterizado(String cpfDescaracterizado) {
        this.cpfDescaracterizado = cpfDescaracterizado;
    }

    public FichaFuncaoDTO dataIngressoFuncao(String dataIngressoFuncao) {
        this.dataIngressoFuncao = dataIngressoFuncao;
        return this;
    }

    /**
     * Get dataIngressoFuncao
     *
     * @return dataIngressoFuncao
     *
     */
    @ApiModelProperty(value = "")
    public String getDataIngressoFuncao() {
        return dataIngressoFuncao;
    }

    public void setDataIngressoFuncao(String dataIngressoFuncao) {
        this.dataIngressoFuncao = dataIngressoFuncao;
    }

    public FichaFuncaoDTO dataIngressoOrgao(String dataIngressoOrgao) {
        this.dataIngressoOrgao = dataIngressoOrgao;
        return this;
    }

    /**
     * Get dataIngressoOrgao
     *
     * @return dataIngressoOrgao
     *
     */
    @ApiModelProperty(value = "")
    public String getDataIngressoOrgao() {
        return dataIngressoOrgao;
    }

    public void setDataIngressoOrgao(String dataIngressoOrgao) {
        this.dataIngressoOrgao = dataIngressoOrgao;
    }

    public FichaFuncaoDTO dataIngressoServicoPublico(String dataIngressoServicoPublico) {
        this.dataIngressoServicoPublico = dataIngressoServicoPublico;
        return this;
    }

    /**
     * Get dataIngressoServicoPublico
     *
     * @return dataIngressoServicoPublico
     *
     */
    @ApiModelProperty(value = "")
    public String getDataIngressoServicoPublico() {
        return dataIngressoServicoPublico;
    }

    public void setDataIngressoServicoPublico(String dataIngressoServicoPublico) {
        this.dataIngressoServicoPublico = dataIngressoServicoPublico;
    }

    public FichaFuncaoDTO dataPublicacaoDocumentoIngressoServicoPublico(String dataPublicacaoDocumentoIngressoServicoPublico) {
        this.dataPublicacaoDocumentoIngressoServicoPublico = dataPublicacaoDocumentoIngressoServicoPublico;
        return this;
    }

    /**
     * Get dataPublicacaoDocumentoIngressoServicoPublico
     *
     * @return dataPublicacaoDocumentoIngressoServicoPublico
     *
     */
    @ApiModelProperty(value = "")
    public String getDataPublicacaoDocumentoIngressoServicoPublico() {
        return dataPublicacaoDocumentoIngressoServicoPublico;
    }

    public void setDataPublicacaoDocumentoIngressoServicoPublico(String dataPublicacaoDocumentoIngressoServicoPublico) {
        this.dataPublicacaoDocumentoIngressoServicoPublico = dataPublicacaoDocumentoIngressoServicoPublico;
    }

    public FichaFuncaoDTO diplomaLegal(String diplomaLegal) {
        this.diplomaLegal = diplomaLegal;
        return this;
    }

    /**
     * Get diplomaLegal
     *
     * @return diplomaLegal
     *
     */
    @ApiModelProperty(value = "")
    public String getDiplomaLegal() {
        return diplomaLegal;
    }

    public void setDiplomaLegal(String diplomaLegal) {
        this.diplomaLegal = diplomaLegal;
    }

    public FichaFuncaoDTO funcao(String funcao) {
        this.funcao = funcao;
        return this;
    }

    /**
     * Get funcao
     *
     * @return funcao
     *
     */
    @ApiModelProperty(value = "")
    public String getFuncao() {
        return funcao;
    }

    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }

    public FichaFuncaoDTO jornadaTrabalho(String jornadaTrabalho) {
        this.jornadaTrabalho = jornadaTrabalho;
        return this;
    }

    /**
     * Get jornadaTrabalho
     *
     * @return jornadaTrabalho
     *
     */
    @ApiModelProperty(value = "")
    public String getJornadaTrabalho() {
        return jornadaTrabalho;
    }

    public void setJornadaTrabalho(String jornadaTrabalho) {
        this.jornadaTrabalho = jornadaTrabalho;
    }

    public FichaFuncaoDTO matriculaDescaracterizada(String matriculaDescaracterizada) {
        this.matriculaDescaracterizada = matriculaDescaracterizada;
        return this;
    }

    /**
     * Get matriculaDescaracterizada
     *
     * @return matriculaDescaracterizada
     *
     */
    @ApiModelProperty(value = "")
    public String getMatriculaDescaracterizada() {
        return matriculaDescaracterizada;
    }

    public void setMatriculaDescaracterizada(String matriculaDescaracterizada) {
        this.matriculaDescaracterizada = matriculaDescaracterizada;
    }

    public FichaFuncaoDTO nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     *
     * @return nome
     *
     */
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public FichaFuncaoDTO opcaoFuncao(String opcaoFuncao) {
        this.opcaoFuncao = opcaoFuncao;
        return this;
    }

    /**
     * Get opcaoFuncao
     *
     * @return opcaoFuncao
     *
     */
    @ApiModelProperty(value = "")
    public String getOpcaoFuncao() {
        return opcaoFuncao;
    }

    public void setOpcaoFuncao(String opcaoFuncao) {
        this.opcaoFuncao = opcaoFuncao;
    }

    public FichaFuncaoDTO orgaoExercicio(String orgaoExercicio) {
        this.orgaoExercicio = orgaoExercicio;
        return this;
    }

    /**
     * Get orgaoExercicio
     *
     * @return orgaoExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoExercicio() {
        return orgaoExercicio;
    }

    public void setOrgaoExercicio(String orgaoExercicio) {
        this.orgaoExercicio = orgaoExercicio;
    }

    public FichaFuncaoDTO orgaoLotacao(String orgaoLotacao) {
        this.orgaoLotacao = orgaoLotacao;
        return this;
    }

    /**
     * Get orgaoLotacao
     *
     * @return orgaoLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoLotacao() {
        return orgaoLotacao;
    }

    public void setOrgaoLotacao(String orgaoLotacao) {
        this.orgaoLotacao = orgaoLotacao;
    }

    public FichaFuncaoDTO orgaoServidorExercicio(String orgaoServidorExercicio) {
        this.orgaoServidorExercicio = orgaoServidorExercicio;
        return this;
    }

    /**
     * Get orgaoServidorExercicio
     *
     * @return orgaoServidorExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoServidorExercicio() {
        return orgaoServidorExercicio;
    }

    public void setOrgaoServidorExercicio(String orgaoServidorExercicio) {
        this.orgaoServidorExercicio = orgaoServidorExercicio;
    }

    public FichaFuncaoDTO orgaoServidorLotacao(String orgaoServidorLotacao) {
        this.orgaoServidorLotacao = orgaoServidorLotacao;
        return this;
    }

    /**
     * Get orgaoServidorLotacao
     *
     * @return orgaoServidorLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoServidorLotacao() {
        return orgaoServidorLotacao;
    }

    public void setOrgaoServidorLotacao(String orgaoServidorLotacao) {
        this.orgaoServidorLotacao = orgaoServidorLotacao;
    }

    public FichaFuncaoDTO orgaoSuperiorExercicio(String orgaoSuperiorExercicio) {
        this.orgaoSuperiorExercicio = orgaoSuperiorExercicio;
        return this;
    }

    /**
     * Get orgaoSuperiorExercicio
     *
     * @return orgaoSuperiorExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoSuperiorExercicio() {
        return orgaoSuperiorExercicio;
    }

    public void setOrgaoSuperiorExercicio(String orgaoSuperiorExercicio) {
        this.orgaoSuperiorExercicio = orgaoSuperiorExercicio;
    }

    public FichaFuncaoDTO orgaoSuperiorLotacao(String orgaoSuperiorLotacao) {
        this.orgaoSuperiorLotacao = orgaoSuperiorLotacao;
        return this;
    }

    /**
     * Get orgaoSuperiorLotacao
     *
     * @return orgaoSuperiorLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoSuperiorLotacao() {
        return orgaoSuperiorLotacao;
    }

    public void setOrgaoSuperiorLotacao(String orgaoSuperiorLotacao) {
        this.orgaoSuperiorLotacao = orgaoSuperiorLotacao;
    }

    public FichaFuncaoDTO regimeJuridico(String regimeJuridico) {
        this.regimeJuridico = regimeJuridico;
        return this;
    }

    /**
     * Get regimeJuridico
     *
     * @return regimeJuridico
     *
     */
    @ApiModelProperty(value = "")
    public String getRegimeJuridico() {
        return regimeJuridico;
    }

    public void setRegimeJuridico(String regimeJuridico) {
        this.regimeJuridico = regimeJuridico;
    }

    public FichaFuncaoDTO situacaoServidor(String situacaoServidor) {
        this.situacaoServidor = situacaoServidor;
        return this;
    }

    /**
     * Get situacaoServidor
     *
     * @return situacaoServidor
     *
     */
    @ApiModelProperty(value = "")
    public String getSituacaoServidor() {
        return situacaoServidor;
    }

    public void setSituacaoServidor(String situacaoServidor) {
        this.situacaoServidor = situacaoServidor;
    }

    public FichaFuncaoDTO ufExercicio(String ufExercicio) {
        this.ufExercicio = ufExercicio;
        return this;
    }

    /**
     * Get ufExercicio
     *
     * @return ufExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getUfExercicio() {
        return ufExercicio;
    }

    public void setUfExercicio(String ufExercicio) {
        this.ufExercicio = ufExercicio;
    }

    public FichaFuncaoDTO uorgExercicio(String uorgExercicio) {
        this.uorgExercicio = uorgExercicio;
        return this;
    }

    /**
     * Get uorgExercicio
     *
     * @return uorgExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getUorgExercicio() {
        return uorgExercicio;
    }

    public void setUorgExercicio(String uorgExercicio) {
        this.uorgExercicio = uorgExercicio;
    }

    public FichaFuncaoDTO uorgLotacao(String uorgLotacao) {
        this.uorgLotacao = uorgLotacao;
        return this;
    }

    /**
     * Get uorgLotacao
     *
     * @return uorgLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getUorgLotacao() {
        return uorgLotacao;
    }

    public void setUorgLotacao(String uorgLotacao) {
        this.uorgLotacao = uorgLotacao;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FichaFuncaoDTO fichaFuncaoDTO = (FichaFuncaoDTO) o;
        return Objects.equals(this.afastamentos, fichaFuncaoDTO.afastamentos)
                && Objects.equals(this.atividade, fichaFuncaoDTO.atividade)
                && Objects.equals(this.cpfDescaracterizado, fichaFuncaoDTO.cpfDescaracterizado)
                && Objects.equals(this.dataIngressoFuncao, fichaFuncaoDTO.dataIngressoFuncao)
                && Objects.equals(this.dataIngressoOrgao, fichaFuncaoDTO.dataIngressoOrgao)
                && Objects.equals(this.dataIngressoServicoPublico, fichaFuncaoDTO.dataIngressoServicoPublico)
                && Objects.equals(this.dataPublicacaoDocumentoIngressoServicoPublico, fichaFuncaoDTO.dataPublicacaoDocumentoIngressoServicoPublico)
                && Objects.equals(this.diplomaLegal, fichaFuncaoDTO.diplomaLegal)
                && Objects.equals(this.funcao, fichaFuncaoDTO.funcao)
                && Objects.equals(this.jornadaTrabalho, fichaFuncaoDTO.jornadaTrabalho)
                && Objects.equals(this.matriculaDescaracterizada, fichaFuncaoDTO.matriculaDescaracterizada)
                && Objects.equals(this.nome, fichaFuncaoDTO.nome)
                && Objects.equals(this.opcaoFuncao, fichaFuncaoDTO.opcaoFuncao)
                && Objects.equals(this.orgaoExercicio, fichaFuncaoDTO.orgaoExercicio)
                && Objects.equals(this.orgaoLotacao, fichaFuncaoDTO.orgaoLotacao)
                && Objects.equals(this.orgaoServidorExercicio, fichaFuncaoDTO.orgaoServidorExercicio)
                && Objects.equals(this.orgaoServidorLotacao, fichaFuncaoDTO.orgaoServidorLotacao)
                && Objects.equals(this.orgaoSuperiorExercicio, fichaFuncaoDTO.orgaoSuperiorExercicio)
                && Objects.equals(this.orgaoSuperiorLotacao, fichaFuncaoDTO.orgaoSuperiorLotacao)
                && Objects.equals(this.regimeJuridico, fichaFuncaoDTO.regimeJuridico)
                && Objects.equals(this.situacaoServidor, fichaFuncaoDTO.situacaoServidor)
                && Objects.equals(this.ufExercicio, fichaFuncaoDTO.ufExercicio)
                && Objects.equals(this.uorgExercicio, fichaFuncaoDTO.uorgExercicio)
                && Objects.equals(this.uorgLotacao, fichaFuncaoDTO.uorgLotacao);
    }

    @Override
    public int hashCode() {
        return Objects.hash(afastamentos, atividade, cpfDescaracterizado, dataIngressoFuncao, dataIngressoOrgao, dataIngressoServicoPublico, dataPublicacaoDocumentoIngressoServicoPublico, diplomaLegal, funcao, jornadaTrabalho, matriculaDescaracterizada, nome, opcaoFuncao, orgaoExercicio, orgaoLotacao, orgaoServidorExercicio, orgaoServidorLotacao, orgaoSuperiorExercicio, orgaoSuperiorLotacao, regimeJuridico, situacaoServidor, ufExercicio, uorgExercicio, uorgLotacao);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FichaFuncaoDTO {\n");

        sb.append("    afastamentos: ").append(toIndentedString(afastamentos)).append("\n");
        sb.append("    atividade: ").append(toIndentedString(atividade)).append("\n");
        sb.append("    cpfDescaracterizado: ").append(toIndentedString(cpfDescaracterizado)).append("\n");
        sb.append("    dataIngressoFuncao: ").append(toIndentedString(dataIngressoFuncao)).append("\n");
        sb.append("    dataIngressoOrgao: ").append(toIndentedString(dataIngressoOrgao)).append("\n");
        sb.append("    dataIngressoServicoPublico: ").append(toIndentedString(dataIngressoServicoPublico)).append("\n");
        sb.append("    dataPublicacaoDocumentoIngressoServicoPublico: ").append(toIndentedString(dataPublicacaoDocumentoIngressoServicoPublico)).append("\n");
        sb.append("    diplomaLegal: ").append(toIndentedString(diplomaLegal)).append("\n");
        sb.append("    funcao: ").append(toIndentedString(funcao)).append("\n");
        sb.append("    jornadaTrabalho: ").append(toIndentedString(jornadaTrabalho)).append("\n");
        sb.append("    matriculaDescaracterizada: ").append(toIndentedString(matriculaDescaracterizada)).append("\n");
        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("    opcaoFuncao: ").append(toIndentedString(opcaoFuncao)).append("\n");
        sb.append("    orgaoExercicio: ").append(toIndentedString(orgaoExercicio)).append("\n");
        sb.append("    orgaoLotacao: ").append(toIndentedString(orgaoLotacao)).append("\n");
        sb.append("    orgaoServidorExercicio: ").append(toIndentedString(orgaoServidorExercicio)).append("\n");
        sb.append("    orgaoServidorLotacao: ").append(toIndentedString(orgaoServidorLotacao)).append("\n");
        sb.append("    orgaoSuperiorExercicio: ").append(toIndentedString(orgaoSuperiorExercicio)).append("\n");
        sb.append("    orgaoSuperiorLotacao: ").append(toIndentedString(orgaoSuperiorLotacao)).append("\n");
        sb.append("    regimeJuridico: ").append(toIndentedString(regimeJuridico)).append("\n");
        sb.append("    situacaoServidor: ").append(toIndentedString(situacaoServidor)).append("\n");
        sb.append("    ufExercicio: ").append(toIndentedString(ufExercicio)).append("\n");
        sb.append("    uorgExercicio: ").append(toIndentedString(uorgExercicio)).append("\n");
        sb.append("    uorgLotacao: ").append(toIndentedString(uorgLotacao)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
