/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * FichaCargoEfetivoDTO
 */
public class FichaCargoEfetivoDTO {

    private List<String> afastamentos = null;

    private String cargo = null;

    private String classeCargo = null;

    private String cpfDescaracterizado = null;

    private String dataIngressoCargo = null;

    private String dataIngressoOrgao = null;

    private String dataIngressoServicoPublico = null;

    private String dataPublicacaoDocumentoIngressoServicoPublico = null;

    private String diplomaLegal = null;

    private String formaIngresso = null;

    private String jornadaTrabalho = null;

    private String matriculaDescaracterizada = null;

    private String nivelCargo = null;

    private String nome = null;

    private String orgaoExercicio = null;

    private String orgaoLotacao = null;

    private String orgaoServidorExercicio = null;

    private String orgaoServidorLotacao = null;

    private String orgaoSuperiorExercicio = null;

    private String orgaoSuperiorLotacao = null;

    private String padraoCargo = null;

    private String regimeJuridico = null;

    private String situacaoServidor = null;

    private String ufExercicio = null;

    private String uorgExercicio = null;

    private String uorgLotacao = null;

    public FichaCargoEfetivoDTO afastamentos(List<String> afastamentos) {
        this.afastamentos = afastamentos;
        return this;
    }

    public FichaCargoEfetivoDTO addAfastamentosItem(String afastamentosItem) {
        if (this.afastamentos == null) {
            this.afastamentos = new ArrayList<String>();
        }
        this.afastamentos.add(afastamentosItem);
        return this;
    }

    /**
     * Get afastamentos
     *
     * @return afastamentos
     *
     */
    @ApiModelProperty(value = "")
    public List<String> getAfastamentos() {
        return afastamentos;
    }

    public void setAfastamentos(List<String> afastamentos) {
        this.afastamentos = afastamentos;
    }

    public FichaCargoEfetivoDTO cargo(String cargo) {
        this.cargo = cargo;
        return this;
    }

    /**
     * Get cargo
     *
     * @return cargo
     *
     */
    @ApiModelProperty(value = "")
    public String getCargo() {
        return cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public FichaCargoEfetivoDTO classeCargo(String classeCargo) {
        this.classeCargo = classeCargo;
        return this;
    }

    /**
     * Get classeCargo
     *
     * @return classeCargo
     *
     */
    @ApiModelProperty(value = "")
    public String getClasseCargo() {
        return classeCargo;
    }

    public void setClasseCargo(String classeCargo) {
        this.classeCargo = classeCargo;
    }

    public FichaCargoEfetivoDTO cpfDescaracterizado(String cpfDescaracterizado) {
        this.cpfDescaracterizado = cpfDescaracterizado;
        return this;
    }

    /**
     * Get cpfDescaracterizado
     *
     * @return cpfDescaracterizado
     *
     */
    @ApiModelProperty(value = "")
    public String getCpfDescaracterizado() {
        return cpfDescaracterizado;
    }

    public void setCpfDescaracterizado(String cpfDescaracterizado) {
        this.cpfDescaracterizado = cpfDescaracterizado;
    }

    public FichaCargoEfetivoDTO dataIngressoCargo(String dataIngressoCargo) {
        this.dataIngressoCargo = dataIngressoCargo;
        return this;
    }

    /**
     * Get dataIngressoCargo
     *
     * @return dataIngressoCargo
     *
     */
    @ApiModelProperty(value = "")
    public String getDataIngressoCargo() {
        return dataIngressoCargo;
    }

    public void setDataIngressoCargo(String dataIngressoCargo) {
        this.dataIngressoCargo = dataIngressoCargo;
    }

    public FichaCargoEfetivoDTO dataIngressoOrgao(String dataIngressoOrgao) {
        this.dataIngressoOrgao = dataIngressoOrgao;
        return this;
    }

    /**
     * Get dataIngressoOrgao
     *
     * @return dataIngressoOrgao
     *
     */
    @ApiModelProperty(value = "")
    public String getDataIngressoOrgao() {
        return dataIngressoOrgao;
    }

    public void setDataIngressoOrgao(String dataIngressoOrgao) {
        this.dataIngressoOrgao = dataIngressoOrgao;
    }

    public FichaCargoEfetivoDTO dataIngressoServicoPublico(String dataIngressoServicoPublico) {
        this.dataIngressoServicoPublico = dataIngressoServicoPublico;
        return this;
    }

    /**
     * Get dataIngressoServicoPublico
     *
     * @return dataIngressoServicoPublico
     *
     */
    @ApiModelProperty(value = "")
    public String getDataIngressoServicoPublico() {
        return dataIngressoServicoPublico;
    }

    public void setDataIngressoServicoPublico(String dataIngressoServicoPublico) {
        this.dataIngressoServicoPublico = dataIngressoServicoPublico;
    }

    public FichaCargoEfetivoDTO dataPublicacaoDocumentoIngressoServicoPublico(String dataPublicacaoDocumentoIngressoServicoPublico) {
        this.dataPublicacaoDocumentoIngressoServicoPublico = dataPublicacaoDocumentoIngressoServicoPublico;
        return this;
    }

    /**
     * Get dataPublicacaoDocumentoIngressoServicoPublico
     *
     * @return dataPublicacaoDocumentoIngressoServicoPublico
     *
     */
    @ApiModelProperty(value = "")
    public String getDataPublicacaoDocumentoIngressoServicoPublico() {
        return dataPublicacaoDocumentoIngressoServicoPublico;
    }

    public void setDataPublicacaoDocumentoIngressoServicoPublico(String dataPublicacaoDocumentoIngressoServicoPublico) {
        this.dataPublicacaoDocumentoIngressoServicoPublico = dataPublicacaoDocumentoIngressoServicoPublico;
    }

    public FichaCargoEfetivoDTO diplomaLegal(String diplomaLegal) {
        this.diplomaLegal = diplomaLegal;
        return this;
    }

    /**
     * Get diplomaLegal
     *
     * @return diplomaLegal
     *
     */
    @ApiModelProperty(value = "")
    public String getDiplomaLegal() {
        return diplomaLegal;
    }

    public void setDiplomaLegal(String diplomaLegal) {
        this.diplomaLegal = diplomaLegal;
    }

    public FichaCargoEfetivoDTO formaIngresso(String formaIngresso) {
        this.formaIngresso = formaIngresso;
        return this;
    }

    /**
     * Get formaIngresso
     *
     * @return formaIngresso
     *
     */
    @ApiModelProperty(value = "")
    public String getFormaIngresso() {
        return formaIngresso;
    }

    public void setFormaIngresso(String formaIngresso) {
        this.formaIngresso = formaIngresso;
    }

    public FichaCargoEfetivoDTO jornadaTrabalho(String jornadaTrabalho) {
        this.jornadaTrabalho = jornadaTrabalho;
        return this;
    }

    /**
     * Get jornadaTrabalho
     *
     * @return jornadaTrabalho
     *
     */
    @ApiModelProperty(value = "")
    public String getJornadaTrabalho() {
        return jornadaTrabalho;
    }

    public void setJornadaTrabalho(String jornadaTrabalho) {
        this.jornadaTrabalho = jornadaTrabalho;
    }

    public FichaCargoEfetivoDTO matriculaDescaracterizada(String matriculaDescaracterizada) {
        this.matriculaDescaracterizada = matriculaDescaracterizada;
        return this;
    }

    /**
     * Get matriculaDescaracterizada
     *
     * @return matriculaDescaracterizada
     *
     */
    @ApiModelProperty(value = "")
    public String getMatriculaDescaracterizada() {
        return matriculaDescaracterizada;
    }

    public void setMatriculaDescaracterizada(String matriculaDescaracterizada) {
        this.matriculaDescaracterizada = matriculaDescaracterizada;
    }

    public FichaCargoEfetivoDTO nivelCargo(String nivelCargo) {
        this.nivelCargo = nivelCargo;
        return this;
    }

    /**
     * Get nivelCargo
     *
     * @return nivelCargo
     *
     */
    @ApiModelProperty(value = "")
    public String getNivelCargo() {
        return nivelCargo;
    }

    public void setNivelCargo(String nivelCargo) {
        this.nivelCargo = nivelCargo;
    }

    public FichaCargoEfetivoDTO nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     *
     * @return nome
     *
     */
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public FichaCargoEfetivoDTO orgaoExercicio(String orgaoExercicio) {
        this.orgaoExercicio = orgaoExercicio;
        return this;
    }

    /**
     * Get orgaoExercicio
     *
     * @return orgaoExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoExercicio() {
        return orgaoExercicio;
    }

    public void setOrgaoExercicio(String orgaoExercicio) {
        this.orgaoExercicio = orgaoExercicio;
    }

    public FichaCargoEfetivoDTO orgaoLotacao(String orgaoLotacao) {
        this.orgaoLotacao = orgaoLotacao;
        return this;
    }

    /**
     * Get orgaoLotacao
     *
     * @return orgaoLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoLotacao() {
        return orgaoLotacao;
    }

    public void setOrgaoLotacao(String orgaoLotacao) {
        this.orgaoLotacao = orgaoLotacao;
    }

    public FichaCargoEfetivoDTO orgaoServidorExercicio(String orgaoServidorExercicio) {
        this.orgaoServidorExercicio = orgaoServidorExercicio;
        return this;
    }

    /**
     * Get orgaoServidorExercicio
     *
     * @return orgaoServidorExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoServidorExercicio() {
        return orgaoServidorExercicio;
    }

    public void setOrgaoServidorExercicio(String orgaoServidorExercicio) {
        this.orgaoServidorExercicio = orgaoServidorExercicio;
    }

    public FichaCargoEfetivoDTO orgaoServidorLotacao(String orgaoServidorLotacao) {
        this.orgaoServidorLotacao = orgaoServidorLotacao;
        return this;
    }

    /**
     * Get orgaoServidorLotacao
     *
     * @return orgaoServidorLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoServidorLotacao() {
        return orgaoServidorLotacao;
    }

    public void setOrgaoServidorLotacao(String orgaoServidorLotacao) {
        this.orgaoServidorLotacao = orgaoServidorLotacao;
    }

    public FichaCargoEfetivoDTO orgaoSuperiorExercicio(String orgaoSuperiorExercicio) {
        this.orgaoSuperiorExercicio = orgaoSuperiorExercicio;
        return this;
    }

    /**
     * Get orgaoSuperiorExercicio
     *
     * @return orgaoSuperiorExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoSuperiorExercicio() {
        return orgaoSuperiorExercicio;
    }

    public void setOrgaoSuperiorExercicio(String orgaoSuperiorExercicio) {
        this.orgaoSuperiorExercicio = orgaoSuperiorExercicio;
    }

    public FichaCargoEfetivoDTO orgaoSuperiorLotacao(String orgaoSuperiorLotacao) {
        this.orgaoSuperiorLotacao = orgaoSuperiorLotacao;
        return this;
    }

    /**
     * Get orgaoSuperiorLotacao
     *
     * @return orgaoSuperiorLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoSuperiorLotacao() {
        return orgaoSuperiorLotacao;
    }

    public void setOrgaoSuperiorLotacao(String orgaoSuperiorLotacao) {
        this.orgaoSuperiorLotacao = orgaoSuperiorLotacao;
    }

    public FichaCargoEfetivoDTO padraoCargo(String padraoCargo) {
        this.padraoCargo = padraoCargo;
        return this;
    }

    /**
     * Get padraoCargo
     *
     * @return padraoCargo
     *
     */
    @ApiModelProperty(value = "")
    public String getPadraoCargo() {
        return padraoCargo;
    }

    public void setPadraoCargo(String padraoCargo) {
        this.padraoCargo = padraoCargo;
    }

    public FichaCargoEfetivoDTO regimeJuridico(String regimeJuridico) {
        this.regimeJuridico = regimeJuridico;
        return this;
    }

    /**
     * Get regimeJuridico
     *
     * @return regimeJuridico
     *
     */
    @ApiModelProperty(value = "")
    public String getRegimeJuridico() {
        return regimeJuridico;
    }

    public void setRegimeJuridico(String regimeJuridico) {
        this.regimeJuridico = regimeJuridico;
    }

    public FichaCargoEfetivoDTO situacaoServidor(String situacaoServidor) {
        this.situacaoServidor = situacaoServidor;
        return this;
    }

    /**
     * Get situacaoServidor
     *
     * @return situacaoServidor
     *
     */
    @ApiModelProperty(value = "")
    public String getSituacaoServidor() {
        return situacaoServidor;
    }

    public void setSituacaoServidor(String situacaoServidor) {
        this.situacaoServidor = situacaoServidor;
    }

    public FichaCargoEfetivoDTO ufExercicio(String ufExercicio) {
        this.ufExercicio = ufExercicio;
        return this;
    }

    /**
     * Get ufExercicio
     *
     * @return ufExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getUfExercicio() {
        return ufExercicio;
    }

    public void setUfExercicio(String ufExercicio) {
        this.ufExercicio = ufExercicio;
    }

    public FichaCargoEfetivoDTO uorgExercicio(String uorgExercicio) {
        this.uorgExercicio = uorgExercicio;
        return this;
    }

    /**
     * Get uorgExercicio
     *
     * @return uorgExercicio
     *
     */
    @ApiModelProperty(value = "")
    public String getUorgExercicio() {
        return uorgExercicio;
    }

    public void setUorgExercicio(String uorgExercicio) {
        this.uorgExercicio = uorgExercicio;
    }

    public FichaCargoEfetivoDTO uorgLotacao(String uorgLotacao) {
        this.uorgLotacao = uorgLotacao;
        return this;
    }

    /**
     * Get uorgLotacao
     *
     * @return uorgLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getUorgLotacao() {
        return uorgLotacao;
    }

    public void setUorgLotacao(String uorgLotacao) {
        this.uorgLotacao = uorgLotacao;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FichaCargoEfetivoDTO fichaCargoEfetivoDTO = (FichaCargoEfetivoDTO) o;
        return Objects.equals(this.afastamentos, fichaCargoEfetivoDTO.afastamentos)
                && Objects.equals(this.cargo, fichaCargoEfetivoDTO.cargo)
                && Objects.equals(this.classeCargo, fichaCargoEfetivoDTO.classeCargo)
                && Objects.equals(this.cpfDescaracterizado, fichaCargoEfetivoDTO.cpfDescaracterizado)
                && Objects.equals(this.dataIngressoCargo, fichaCargoEfetivoDTO.dataIngressoCargo)
                && Objects.equals(this.dataIngressoOrgao, fichaCargoEfetivoDTO.dataIngressoOrgao)
                && Objects.equals(this.dataIngressoServicoPublico, fichaCargoEfetivoDTO.dataIngressoServicoPublico)
                && Objects.equals(this.dataPublicacaoDocumentoIngressoServicoPublico, fichaCargoEfetivoDTO.dataPublicacaoDocumentoIngressoServicoPublico)
                && Objects.equals(this.diplomaLegal, fichaCargoEfetivoDTO.diplomaLegal)
                && Objects.equals(this.formaIngresso, fichaCargoEfetivoDTO.formaIngresso)
                && Objects.equals(this.jornadaTrabalho, fichaCargoEfetivoDTO.jornadaTrabalho)
                && Objects.equals(this.matriculaDescaracterizada, fichaCargoEfetivoDTO.matriculaDescaracterizada)
                && Objects.equals(this.nivelCargo, fichaCargoEfetivoDTO.nivelCargo)
                && Objects.equals(this.nome, fichaCargoEfetivoDTO.nome)
                && Objects.equals(this.orgaoExercicio, fichaCargoEfetivoDTO.orgaoExercicio)
                && Objects.equals(this.orgaoLotacao, fichaCargoEfetivoDTO.orgaoLotacao)
                && Objects.equals(this.orgaoServidorExercicio, fichaCargoEfetivoDTO.orgaoServidorExercicio)
                && Objects.equals(this.orgaoServidorLotacao, fichaCargoEfetivoDTO.orgaoServidorLotacao)
                && Objects.equals(this.orgaoSuperiorExercicio, fichaCargoEfetivoDTO.orgaoSuperiorExercicio)
                && Objects.equals(this.orgaoSuperiorLotacao, fichaCargoEfetivoDTO.orgaoSuperiorLotacao)
                && Objects.equals(this.padraoCargo, fichaCargoEfetivoDTO.padraoCargo)
                && Objects.equals(this.regimeJuridico, fichaCargoEfetivoDTO.regimeJuridico)
                && Objects.equals(this.situacaoServidor, fichaCargoEfetivoDTO.situacaoServidor)
                && Objects.equals(this.ufExercicio, fichaCargoEfetivoDTO.ufExercicio)
                && Objects.equals(this.uorgExercicio, fichaCargoEfetivoDTO.uorgExercicio)
                && Objects.equals(this.uorgLotacao, fichaCargoEfetivoDTO.uorgLotacao);
    }

    @Override
    public int hashCode() {
        return Objects.hash(afastamentos, cargo, classeCargo, cpfDescaracterizado, dataIngressoCargo, dataIngressoOrgao, dataIngressoServicoPublico, dataPublicacaoDocumentoIngressoServicoPublico, diplomaLegal, formaIngresso, jornadaTrabalho, matriculaDescaracterizada, nivelCargo, nome, orgaoExercicio, orgaoLotacao, orgaoServidorExercicio, orgaoServidorLotacao, orgaoSuperiorExercicio, orgaoSuperiorLotacao, padraoCargo, regimeJuridico, situacaoServidor, ufExercicio, uorgExercicio, uorgLotacao);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FichaCargoEfetivoDTO {\n");

        sb.append("    afastamentos: ").append(toIndentedString(afastamentos)).append("\n");
        sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
        sb.append("    classeCargo: ").append(toIndentedString(classeCargo)).append("\n");
        sb.append("    cpfDescaracterizado: ").append(toIndentedString(cpfDescaracterizado)).append("\n");
        sb.append("    dataIngressoCargo: ").append(toIndentedString(dataIngressoCargo)).append("\n");
        sb.append("    dataIngressoOrgao: ").append(toIndentedString(dataIngressoOrgao)).append("\n");
        sb.append("    dataIngressoServicoPublico: ").append(toIndentedString(dataIngressoServicoPublico)).append("\n");
        sb.append("    dataPublicacaoDocumentoIngressoServicoPublico: ").append(toIndentedString(dataPublicacaoDocumentoIngressoServicoPublico)).append("\n");
        sb.append("    diplomaLegal: ").append(toIndentedString(diplomaLegal)).append("\n");
        sb.append("    formaIngresso: ").append(toIndentedString(formaIngresso)).append("\n");
        sb.append("    jornadaTrabalho: ").append(toIndentedString(jornadaTrabalho)).append("\n");
        sb.append("    matriculaDescaracterizada: ").append(toIndentedString(matriculaDescaracterizada)).append("\n");
        sb.append("    nivelCargo: ").append(toIndentedString(nivelCargo)).append("\n");
        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("    orgaoExercicio: ").append(toIndentedString(orgaoExercicio)).append("\n");
        sb.append("    orgaoLotacao: ").append(toIndentedString(orgaoLotacao)).append("\n");
        sb.append("    orgaoServidorExercicio: ").append(toIndentedString(orgaoServidorExercicio)).append("\n");
        sb.append("    orgaoServidorLotacao: ").append(toIndentedString(orgaoServidorLotacao)).append("\n");
        sb.append("    orgaoSuperiorExercicio: ").append(toIndentedString(orgaoSuperiorExercicio)).append("\n");
        sb.append("    orgaoSuperiorLotacao: ").append(toIndentedString(orgaoSuperiorLotacao)).append("\n");
        sb.append("    padraoCargo: ").append(toIndentedString(padraoCargo)).append("\n");
        sb.append("    regimeJuridico: ").append(toIndentedString(regimeJuridico)).append("\n");
        sb.append("    situacaoServidor: ").append(toIndentedString(situacaoServidor)).append("\n");
        sb.append("    ufExercicio: ").append(toIndentedString(ufExercicio)).append("\n");
        sb.append("    uorgExercicio: ").append(toIndentedString(uorgExercicio)).append("\n");
        sb.append("    uorgLotacao: ").append(toIndentedString(uorgLotacao)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
