/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * FichaMilitarDTO
 */
public class FichaMilitarDTO {

    private List<String> afastamentos = null;

    private String cargo = null;

    private String cpfDescaracterizado = null;

    private String dataIngressoOrgao = null;

    private String dataPublicacaoDocumentoIngressoServicoPublico = null;

    private String diplomaLegal = null;

    private String jornadaTrabalho = null;

    private String matriculaDescaracterizada = null;

    private String nome = null;

    private String orgao = null;

    private String orgaoServidorLotacao = null;

    private String orgaoSuperior = null;

    private String regimeJuridico = null;

    private String situacaoServidor = null;

    public FichaMilitarDTO afastamentos(List<String> afastamentos) {
        this.afastamentos = afastamentos;
        return this;
    }

    public FichaMilitarDTO addAfastamentosItem(String afastamentosItem) {
        if (this.afastamentos == null) {
            this.afastamentos = new ArrayList<String>();
        }
        this.afastamentos.add(afastamentosItem);
        return this;
    }

    /**
     * Get afastamentos
     *
     * @return afastamentos
     *
     */
    @ApiModelProperty(value = "")
    public List<String> getAfastamentos() {
        return afastamentos;
    }

    public void setAfastamentos(List<String> afastamentos) {
        this.afastamentos = afastamentos;
    }

    public FichaMilitarDTO cargo(String cargo) {
        this.cargo = cargo;
        return this;
    }

    /**
     * Get cargo
     *
     * @return cargo
     *
     */
    @ApiModelProperty(value = "")
    public String getCargo() {
        return cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    public FichaMilitarDTO cpfDescaracterizado(String cpfDescaracterizado) {
        this.cpfDescaracterizado = cpfDescaracterizado;
        return this;
    }

    /**
     * Get cpfDescaracterizado
     *
     * @return cpfDescaracterizado
     *
     */
    @ApiModelProperty(value = "")
    public String getCpfDescaracterizado() {
        return cpfDescaracterizado;
    }

    public void setCpfDescaracterizado(String cpfDescaracterizado) {
        this.cpfDescaracterizado = cpfDescaracterizado;
    }

    public FichaMilitarDTO dataIngressoOrgao(String dataIngressoOrgao) {
        this.dataIngressoOrgao = dataIngressoOrgao;
        return this;
    }

    /**
     * Get dataIngressoOrgao
     *
     * @return dataIngressoOrgao
     *
     */
    @ApiModelProperty(value = "")
    public String getDataIngressoOrgao() {
        return dataIngressoOrgao;
    }

    public void setDataIngressoOrgao(String dataIngressoOrgao) {
        this.dataIngressoOrgao = dataIngressoOrgao;
    }

    public FichaMilitarDTO dataPublicacaoDocumentoIngressoServicoPublico(String dataPublicacaoDocumentoIngressoServicoPublico) {
        this.dataPublicacaoDocumentoIngressoServicoPublico = dataPublicacaoDocumentoIngressoServicoPublico;
        return this;
    }

    /**
     * Get dataPublicacaoDocumentoIngressoServicoPublico
     *
     * @return dataPublicacaoDocumentoIngressoServicoPublico
     *
     */
    @ApiModelProperty(value = "")
    public String getDataPublicacaoDocumentoIngressoServicoPublico() {
        return dataPublicacaoDocumentoIngressoServicoPublico;
    }

    public void setDataPublicacaoDocumentoIngressoServicoPublico(String dataPublicacaoDocumentoIngressoServicoPublico) {
        this.dataPublicacaoDocumentoIngressoServicoPublico = dataPublicacaoDocumentoIngressoServicoPublico;
    }

    public FichaMilitarDTO diplomaLegal(String diplomaLegal) {
        this.diplomaLegal = diplomaLegal;
        return this;
    }

    /**
     * Get diplomaLegal
     *
     * @return diplomaLegal
     *
     */
    @ApiModelProperty(value = "")
    public String getDiplomaLegal() {
        return diplomaLegal;
    }

    public void setDiplomaLegal(String diplomaLegal) {
        this.diplomaLegal = diplomaLegal;
    }

    public FichaMilitarDTO jornadaTrabalho(String jornadaTrabalho) {
        this.jornadaTrabalho = jornadaTrabalho;
        return this;
    }

    /**
     * Get jornadaTrabalho
     *
     * @return jornadaTrabalho
     *
     */
    @ApiModelProperty(value = "")
    public String getJornadaTrabalho() {
        return jornadaTrabalho;
    }

    public void setJornadaTrabalho(String jornadaTrabalho) {
        this.jornadaTrabalho = jornadaTrabalho;
    }

    public FichaMilitarDTO matriculaDescaracterizada(String matriculaDescaracterizada) {
        this.matriculaDescaracterizada = matriculaDescaracterizada;
        return this;
    }

    /**
     * Get matriculaDescaracterizada
     *
     * @return matriculaDescaracterizada
     *
     */
    @ApiModelProperty(value = "")
    public String getMatriculaDescaracterizada() {
        return matriculaDescaracterizada;
    }

    public void setMatriculaDescaracterizada(String matriculaDescaracterizada) {
        this.matriculaDescaracterizada = matriculaDescaracterizada;
    }

    public FichaMilitarDTO nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     *
     * @return nome
     *
     */
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public FichaMilitarDTO orgao(String orgao) {
        this.orgao = orgao;
        return this;
    }

    /**
     * Get orgao
     *
     * @return orgao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgao() {
        return orgao;
    }

    public void setOrgao(String orgao) {
        this.orgao = orgao;
    }

    public FichaMilitarDTO orgaoServidorLotacao(String orgaoServidorLotacao) {
        this.orgaoServidorLotacao = orgaoServidorLotacao;
        return this;
    }

    /**
     * Get orgaoServidorLotacao
     *
     * @return orgaoServidorLotacao
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoServidorLotacao() {
        return orgaoServidorLotacao;
    }

    public void setOrgaoServidorLotacao(String orgaoServidorLotacao) {
        this.orgaoServidorLotacao = orgaoServidorLotacao;
    }

    public FichaMilitarDTO orgaoSuperior(String orgaoSuperior) {
        this.orgaoSuperior = orgaoSuperior;
        return this;
    }

    /**
     * Get orgaoSuperior
     *
     * @return orgaoSuperior
     *
     */
    @ApiModelProperty(value = "")
    public String getOrgaoSuperior() {
        return orgaoSuperior;
    }

    public void setOrgaoSuperior(String orgaoSuperior) {
        this.orgaoSuperior = orgaoSuperior;
    }

    public FichaMilitarDTO regimeJuridico(String regimeJuridico) {
        this.regimeJuridico = regimeJuridico;
        return this;
    }

    /**
     * Get regimeJuridico
     *
     * @return regimeJuridico
     *
     */
    @ApiModelProperty(value = "")
    public String getRegimeJuridico() {
        return regimeJuridico;
    }

    public void setRegimeJuridico(String regimeJuridico) {
        this.regimeJuridico = regimeJuridico;
    }

    public FichaMilitarDTO situacaoServidor(String situacaoServidor) {
        this.situacaoServidor = situacaoServidor;
        return this;
    }

    /**
     * Get situacaoServidor
     *
     * @return situacaoServidor
     *
     */
    @ApiModelProperty(value = "")
    public String getSituacaoServidor() {
        return situacaoServidor;
    }

    public void setSituacaoServidor(String situacaoServidor) {
        this.situacaoServidor = situacaoServidor;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FichaMilitarDTO fichaMilitarDTO = (FichaMilitarDTO) o;
        return Objects.equals(this.afastamentos, fichaMilitarDTO.afastamentos)
                && Objects.equals(this.cargo, fichaMilitarDTO.cargo)
                && Objects.equals(this.cpfDescaracterizado, fichaMilitarDTO.cpfDescaracterizado)
                && Objects.equals(this.dataIngressoOrgao, fichaMilitarDTO.dataIngressoOrgao)
                && Objects.equals(this.dataPublicacaoDocumentoIngressoServicoPublico, fichaMilitarDTO.dataPublicacaoDocumentoIngressoServicoPublico)
                && Objects.equals(this.diplomaLegal, fichaMilitarDTO.diplomaLegal)
                && Objects.equals(this.jornadaTrabalho, fichaMilitarDTO.jornadaTrabalho)
                && Objects.equals(this.matriculaDescaracterizada, fichaMilitarDTO.matriculaDescaracterizada)
                && Objects.equals(this.nome, fichaMilitarDTO.nome)
                && Objects.equals(this.orgao, fichaMilitarDTO.orgao)
                && Objects.equals(this.orgaoServidorLotacao, fichaMilitarDTO.orgaoServidorLotacao)
                && Objects.equals(this.orgaoSuperior, fichaMilitarDTO.orgaoSuperior)
                && Objects.equals(this.regimeJuridico, fichaMilitarDTO.regimeJuridico)
                && Objects.equals(this.situacaoServidor, fichaMilitarDTO.situacaoServidor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(afastamentos, cargo, cpfDescaracterizado, dataIngressoOrgao, dataPublicacaoDocumentoIngressoServicoPublico, diplomaLegal, jornadaTrabalho, matriculaDescaracterizada, nome, orgao, orgaoServidorLotacao, orgaoSuperior, regimeJuridico, situacaoServidor);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FichaMilitarDTO {\n");

        sb.append("    afastamentos: ").append(toIndentedString(afastamentos)).append("\n");
        sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
        sb.append("    cpfDescaracterizado: ").append(toIndentedString(cpfDescaracterizado)).append("\n");
        sb.append("    dataIngressoOrgao: ").append(toIndentedString(dataIngressoOrgao)).append("\n");
        sb.append("    dataPublicacaoDocumentoIngressoServicoPublico: ").append(toIndentedString(dataPublicacaoDocumentoIngressoServicoPublico)).append("\n");
        sb.append("    diplomaLegal: ").append(toIndentedString(diplomaLegal)).append("\n");
        sb.append("    jornadaTrabalho: ").append(toIndentedString(jornadaTrabalho)).append("\n");
        sb.append("    matriculaDescaracterizada: ").append(toIndentedString(matriculaDescaracterizada)).append("\n");
        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("    orgao: ").append(toIndentedString(orgao)).append("\n");
        sb.append("    orgaoServidorLotacao: ").append(toIndentedString(orgaoServidorLotacao)).append("\n");
        sb.append("    orgaoSuperior: ").append(toIndentedString(orgaoSuperior)).append("\n");
        sb.append("    regimeJuridico: ").append(toIndentedString(regimeJuridico)).append("\n");
        sb.append("    situacaoServidor: ").append(toIndentedString(situacaoServidor)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
