/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * JetomDTO
 */
public class JetomDTO {

    private String descricao = null;

    private String mesReferencia = null;

    private BigDecimal valor = null;

    public JetomDTO descricao(String descricao) {
        this.descricao = descricao;
        return this;
    }

    /**
     * Get descricao
     *
     * @return descricao
     *
     */
    @ApiModelProperty(value = "")
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public JetomDTO mesReferencia(String mesReferencia) {
        this.mesReferencia = mesReferencia;
        return this;
    }

    /**
     * Get mesReferencia
     *
     * @return mesReferencia
     *
     */
    @ApiModelProperty(value = "")
    public String getMesReferencia() {
        return mesReferencia;
    }

    public void setMesReferencia(String mesReferencia) {
        this.mesReferencia = mesReferencia;
    }

    public JetomDTO valor(BigDecimal valor) {
        this.valor = valor;
        return this;
    }

    /**
     * Get valor
     *
     * @return valor
     *
     */
    @ApiModelProperty(value = "")
    public BigDecimal getValor() {
        return valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JetomDTO jetomDTO = (JetomDTO) o;
        return Objects.equals(this.descricao, jetomDTO.descricao)
                && Objects.equals(this.mesReferencia, jetomDTO.mesReferencia)
                && Objects.equals(this.valor, jetomDTO.valor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(descricao, mesReferencia, valor);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JetomDTO {\n");

        sb.append("    descricao: ").append(toIndentedString(descricao)).append("\n");
        sb.append("    mesReferencia: ").append(toIndentedString(mesReferencia)).append("\n");
        sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
