/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * OrgaoCeafDTO
 */
public class OrgaoCeafDTO {

    private String nome = null;

    private String nomeSemAcento = null;

    private String sigla = null;

    private String siglaDaPasta = null;

    public OrgaoCeafDTO nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     *
     * @return nome
     *
     */
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public OrgaoCeafDTO nomeSemAcento(String nomeSemAcento) {
        this.nomeSemAcento = nomeSemAcento;
        return this;
    }

    /**
     * Get nomeSemAcento
     *
     * @return nomeSemAcento
     *
     */
    @ApiModelProperty(value = "")
    public String getNomeSemAcento() {
        return nomeSemAcento;
    }

    public void setNomeSemAcento(String nomeSemAcento) {
        this.nomeSemAcento = nomeSemAcento;
    }

    public OrgaoCeafDTO sigla(String sigla) {
        this.sigla = sigla;
        return this;
    }

    /**
     * Get sigla
     *
     * @return sigla
     *
     */
    @ApiModelProperty(value = "")
    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public OrgaoCeafDTO siglaDaPasta(String siglaDaPasta) {
        this.siglaDaPasta = siglaDaPasta;
        return this;
    }

    /**
     * Get siglaDaPasta
     *
     * @return siglaDaPasta
     *
     */
    @ApiModelProperty(value = "")
    public String getSiglaDaPasta() {
        return siglaDaPasta;
    }

    public void setSiglaDaPasta(String siglaDaPasta) {
        this.siglaDaPasta = siglaDaPasta;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrgaoCeafDTO orgaoCeafDTO = (OrgaoCeafDTO) o;
        return Objects.equals(this.nome, orgaoCeafDTO.nome)
                && Objects.equals(this.nomeSemAcento, orgaoCeafDTO.nomeSemAcento)
                && Objects.equals(this.sigla, orgaoCeafDTO.sigla)
                && Objects.equals(this.siglaDaPasta, orgaoCeafDTO.siglaDaPasta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nome, nomeSemAcento, sigla, siglaDaPasta);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrgaoCeafDTO {\n");

        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("    nomeSemAcento: ").append(toIndentedString(nomeSemAcento)).append("\n");
        sb.append("    sigla: ").append(toIndentedString(sigla)).append("\n");
        sb.append("    siglaDaPasta: ").append(toIndentedString(siglaDaPasta)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
