/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * ParticipanteLicitacaoDTO
 */
public class ParticipanteLicitacaoDTO {

    private String cpfCnpj = null;

    private String idParticipante = null;

    private String nome = null;

    private String tipoParticipante = null;

    public ParticipanteLicitacaoDTO cpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
        return this;
    }

    /**
     * Get cpfCnpj
     *
     * @return cpfCnpj
     *
     */
    @ApiModelProperty(value = "")
    public String getCpfCnpj() {
        return cpfCnpj;
    }

    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }

    public ParticipanteLicitacaoDTO idParticipante(String idParticipante) {
        this.idParticipante = idParticipante;
        return this;
    }

    /**
     * Get idParticipante
     *
     * @return idParticipante
     *
     */
    @ApiModelProperty(value = "")
    public String getIdParticipante() {
        return idParticipante;
    }

    public void setIdParticipante(String idParticipante) {
        this.idParticipante = idParticipante;
    }

    public ParticipanteLicitacaoDTO nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     *
     * @return nome
     *
     */
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public ParticipanteLicitacaoDTO tipoParticipante(String tipoParticipante) {
        this.tipoParticipante = tipoParticipante;
        return this;
    }

    /**
     * Get tipoParticipante
     *
     * @return tipoParticipante
     *
     */
    @ApiModelProperty(value = "")
    public String getTipoParticipante() {
        return tipoParticipante;
    }

    public void setTipoParticipante(String tipoParticipante) {
        this.tipoParticipante = tipoParticipante;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ParticipanteLicitacaoDTO participanteLicitacaoDTO = (ParticipanteLicitacaoDTO) o;
        return Objects.equals(this.cpfCnpj, participanteLicitacaoDTO.cpfCnpj)
                && Objects.equals(this.idParticipante, participanteLicitacaoDTO.idParticipante)
                && Objects.equals(this.nome, participanteLicitacaoDTO.nome)
                && Objects.equals(this.tipoParticipante, participanteLicitacaoDTO.tipoParticipante);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cpfCnpj, idParticipante, nome, tipoParticipante);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ParticipanteLicitacaoDTO {\n");

        sb.append("    cpfCnpj: ").append(toIndentedString(cpfCnpj)).append("\n");
        sb.append("    idParticipante: ").append(toIndentedString(idParticipante)).append("\n");
        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("    tipoParticipante: ").append(toIndentedString(tipoParticipante)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
