/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * PunicaoDTO
 */
public class PunicaoDTO {

    private String cpfPunidoFormatado = null;

    private String nomePunido = null;

    private String paginaDOU = null;

    private String portaria = null;

    private String processo = null;

    private String secaoDOU = null;

    public PunicaoDTO cpfPunidoFormatado(String cpfPunidoFormatado) {
        this.cpfPunidoFormatado = cpfPunidoFormatado;
        return this;
    }

    /**
     * Get cpfPunidoFormatado
     *
     * @return cpfPunidoFormatado
     *
     */
    @ApiModelProperty(value = "")
    public String getCpfPunidoFormatado() {
        return cpfPunidoFormatado;
    }

    public void setCpfPunidoFormatado(String cpfPunidoFormatado) {
        this.cpfPunidoFormatado = cpfPunidoFormatado;
    }

    public PunicaoDTO nomePunido(String nomePunido) {
        this.nomePunido = nomePunido;
        return this;
    }

    /**
     * Get nomePunido
     *
     * @return nomePunido
     *
     */
    @ApiModelProperty(value = "")
    public String getNomePunido() {
        return nomePunido;
    }

    public void setNomePunido(String nomePunido) {
        this.nomePunido = nomePunido;
    }

    public PunicaoDTO paginaDOU(String paginaDOU) {
        this.paginaDOU = paginaDOU;
        return this;
    }

    /**
     * Get paginaDOU
     *
     * @return paginaDOU
     *
     */
    @ApiModelProperty(value = "")
    public String getPaginaDOU() {
        return paginaDOU;
    }

    public void setPaginaDOU(String paginaDOU) {
        this.paginaDOU = paginaDOU;
    }

    public PunicaoDTO portaria(String portaria) {
        this.portaria = portaria;
        return this;
    }

    /**
     * Get portaria
     *
     * @return portaria
     *
     */
    @ApiModelProperty(value = "")
    public String getPortaria() {
        return portaria;
    }

    public void setPortaria(String portaria) {
        this.portaria = portaria;
    }

    public PunicaoDTO processo(String processo) {
        this.processo = processo;
        return this;
    }

    /**
     * Get processo
     *
     * @return processo
     *
     */
    @ApiModelProperty(value = "")
    public String getProcesso() {
        return processo;
    }

    public void setProcesso(String processo) {
        this.processo = processo;
    }

    public PunicaoDTO secaoDOU(String secaoDOU) {
        this.secaoDOU = secaoDOU;
        return this;
    }

    /**
     * Get secaoDOU
     *
     * @return secaoDOU
     *
     */
    @ApiModelProperty(value = "")
    public String getSecaoDOU() {
        return secaoDOU;
    }

    public void setSecaoDOU(String secaoDOU) {
        this.secaoDOU = secaoDOU;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PunicaoDTO punicaoDTO = (PunicaoDTO) o;
        return Objects.equals(this.cpfPunidoFormatado, punicaoDTO.cpfPunidoFormatado)
                && Objects.equals(this.nomePunido, punicaoDTO.nomePunido)
                && Objects.equals(this.paginaDOU, punicaoDTO.paginaDOU)
                && Objects.equals(this.portaria, punicaoDTO.portaria)
                && Objects.equals(this.processo, punicaoDTO.processo)
                && Objects.equals(this.secaoDOU, punicaoDTO.secaoDOU);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cpfPunidoFormatado, nomePunido, paginaDOU, portaria, processo, secaoDOU);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PunicaoDTO {\n");

        sb.append("    cpfPunidoFormatado: ").append(toIndentedString(cpfPunidoFormatado)).append("\n");
        sb.append("    nomePunido: ").append(toIndentedString(nomePunido)).append("\n");
        sb.append("    paginaDOU: ").append(toIndentedString(paginaDOU)).append("\n");
        sb.append("    portaria: ").append(toIndentedString(portaria)).append("\n");
        sb.append("    processo: ").append(toIndentedString(processo)).append("\n");
        sb.append("    secaoDOU: ").append(toIndentedString(secaoDOU)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
