/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ServidorRemuneracaoDTO
 */
public class ServidorRemuneracaoDTO {

    private List<RemuneracaoDTO> remuneracoesDTO = null;
    private ServidorAposentadoPensionistaDTO servidor = null;

    public ServidorRemuneracaoDTO remuneracoesDTO(List<RemuneracaoDTO> remuneracoesDTO) {
        this.remuneracoesDTO = remuneracoesDTO;
        return this;
    }

    public ServidorRemuneracaoDTO addRemuneracoesDTOItem(RemuneracaoDTO remuneracoesDTOItem) {
        if (this.remuneracoesDTO == null) {
            this.remuneracoesDTO = new ArrayList<RemuneracaoDTO>();
        }
        this.remuneracoesDTO.add(remuneracoesDTOItem);
        return this;
    }

    /**
     * Get remuneracoesDTO
     *
     * @return remuneracoesDTO
     *
     */
    @ApiModelProperty(value = "")
    public List<RemuneracaoDTO> getRemuneracoesDTO() {
        return remuneracoesDTO;
    }

    public void setRemuneracoesDTO(List<RemuneracaoDTO> remuneracoesDTO) {
        this.remuneracoesDTO = remuneracoesDTO;
    }

    public ServidorRemuneracaoDTO servidor(ServidorAposentadoPensionistaDTO servidor) {
        this.servidor = servidor;
        return this;
    }

    /**
     * Get servidor
     *
     * @return servidor
     *
     */
    @ApiModelProperty(value = "")
    public ServidorAposentadoPensionistaDTO getServidor() {
        return servidor;
    }

    public void setServidor(ServidorAposentadoPensionistaDTO servidor) {
        this.servidor = servidor;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServidorRemuneracaoDTO servidorRemuneracaoDTO = (ServidorRemuneracaoDTO) o;
        return Objects.equals(this.remuneracoesDTO, servidorRemuneracaoDTO.remuneracoesDTO)
                && Objects.equals(this.servidor, servidorRemuneracaoDTO.servidor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(remuneracoesDTO, servidor);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ServidorRemuneracaoDTO {\n");

        sb.append("    remuneracoesDTO: ").append(toIndentedString(remuneracoesDTO)).append("\n");
        sb.append("    servidor: ").append(toIndentedString(servidor)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
