/*
 * API REST do Portal da Transparência do Governo Federal
 * API de serviços do Portal da Transparência do Governo Federal
 *
 * OpenAPI spec version: 1.0
 * Contact: listaapitransparencia@cgu.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.harpia.stive.domain.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * ServidorInativoDTO
 */
public class ServidorInativoDTO {

    private String cpfFormatado = null;

    private Integer id = null;

    private String nome = null;

    public ServidorInativoDTO cpfFormatado(String cpfFormatado) {
        this.cpfFormatado = cpfFormatado;
        return this;
    }

    /**
     * Get cpfFormatado
     *
     * @return cpfFormatado
     *
     */
    @ApiModelProperty(value = "")
    public String getCpfFormatado() {
        return cpfFormatado;
    }

    public void setCpfFormatado(String cpfFormatado) {
        this.cpfFormatado = cpfFormatado;
    }

    public ServidorInativoDTO id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     *
     */
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ServidorInativoDTO nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     *
     * @return nome
     *
     */
    @ApiModelProperty(value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServidorInativoDTO servidorInativoDTO = (ServidorInativoDTO) o;
        return Objects.equals(this.cpfFormatado, servidorInativoDTO.cpfFormatado)
                && Objects.equals(this.id, servidorInativoDTO.id)
                && Objects.equals(this.nome, servidorInativoDTO.nome);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cpfFormatado, id, nome);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ServidorInativoDTO {\n");

        sb.append("    cpfFormatado: ").append(toIndentedString(cpfFormatado)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
